version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule: { interval: weekly }
    groups: { actions: { patterns: ['*'] } }
  - package-ecosystem: npm
    directory: /
    schedule: { interval: weekly }
    groups: { firebase-tooling: { patterns: ['*'] } }
  - package-ecosystem: pub
    directory: /
    schedule: { interval: weekly }
