#!/usr/bin/env node
// Generates RBAC artifacts from firebase/rules-src/permissions.json:
//   firebase/firestore.rules              (from firestore.rules.tmpl + perms() map)
//   functions/src/generated/rbac.ts       (roles, codes, permissions, grantable)
//   apps/web/src/generated/rbac.ts        (same, for UI decisions only)
// `--check` exits non-zero if any generated file is stale (used in CI).
import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = fileURLToPath(new URL('../../', import.meta.url));
const src = JSON.parse(readFileSync(join(root, 'firebase/rules-src/permissions.json'), 'utf8'));
const strip = (o) => Object.fromEntries(Object.entries(o).filter(([k]) => !k.startsWith('$')));
const roles = strip(src.roles);
const permissions = strip(src.permissions);
const grantable = strip(src.grantable);

// Validate references so a typo fails generation instead of silently denying.
const codes = new Set(Object.values(roles).map((r) => r.code));
for (const [perm, list] of Object.entries(permissions)) {
  for (const c of list) if (!codes.has(c) || c === 'SA') throw new Error(`${perm}: unknown or platform role code ${c}`);
}
for (const [role, list] of Object.entries(grantable)) {
  if (!roles[role]) throw new Error(`grantable: unknown role ${role}`);
  for (const r of list) if (!roles[r] || roles[r].scope === 'platform') throw new Error(`grantable.${role}: bad role ${r}`);
}

const header = '// GENERATED by tools/rbac/generate.mjs from firebase/rules-src/permissions.json. Do not edit.\n';

const permsFn =
  '    // GENERATED permission → role-code map (tools/rbac/generate.mjs). Do not edit here.\n' +
  '    function perms() {\n      return {\n' +
  Object.entries(permissions)
    .map(([p, list]) => `        '${p}': [${list.map((c) => `'${c}'`).join(', ')}]`)
    .join(',\n') +
  '\n      };\n    }';
const tmpl = readFileSync(join(root, 'firebase/rules-src/firestore.rules.tmpl'), 'utf8');
if (!tmpl.includes('/*@@PERMISSIONS@@*/')) throw new Error('template is missing /*@@PERMISSIONS@@*/');
const rules = '// GENERATED from firebase/rules-src/firestore.rules.tmpl. Edit the template, then `npm run gen:rbac`.\n' +
  tmpl.replace('    /*@@PERMISSIONS@@*/', permsFn);
if (/allow\s+read\s*,\s*write\s*:\s*if\s+request\.auth\s*!=\s*null/.test(rules)) {
  throw new Error('Refusing to generate rules containing a blanket signed-in read/write grant');
}

const ts =
  header +
  `export const ROLES = ${JSON.stringify(roles, null, 2)} as const;\n\n` +
  `export type Role = keyof typeof ROLES;\n` +
  `export type RoleCode = (typeof ROLES)[Role]['code'];\n\n` +
  `export const PERMISSIONS = ${JSON.stringify(permissions, null, 2)} as const satisfies Record<string, readonly string[]>;\n\n` +
  `export type Permission = keyof typeof PERMISSIONS;\n\n` +
  `export const GRANTABLE: Partial<Record<Role, readonly Role[]>> = ${JSON.stringify(grantable, null, 2)};\n`;

const outputs = {
  'firebase/firestore.rules': rules,
  'functions/src/generated/rbac.ts': ts,
  'apps/web/src/generated/rbac.ts': ts,
};

const check = process.argv.includes('--check');
let stale = false;
for (const [rel, content] of Object.entries(outputs)) {
  const path = join(root, rel);
  const current = existsSync(path) ? readFileSync(path, 'utf8') : null;
  if (current === content) continue;
  if (check) {
    console.error(`stale: ${rel} (run npm run gen:rbac)`);
    stale = true;
  } else {
    mkdirSync(dirname(path), { recursive: true });
    writeFileSync(path, content);
    console.log(`wrote ${rel}`);
  }
}
if (stale) process.exit(1);
