// User-facing copy for the Phase 1 library screens (kept out of components for i18n).
export const lt = {
  // catalogue
  catalogueTitle: 'Catalogue',
  searchBooks: 'Search by title, author, ISBN or code',
  allAges: 'All ages',
  newBook: 'New book',
  editBook: 'Edit book',
  referenceData: 'Authors, publishers & categories',
  booksEmpty: 'No books match.',
  booksEmptyHint: 'Try a shorter search, or add the title to the catalogue.',
  title: 'Title',
  subtitle: 'Subtitle (optional)',
  isbn: 'ISBN (optional)',
  isbnHint: 'ISBN-10 or ISBN-13; hyphens are fine.',
  authors: 'Authors',
  publisher: 'Publisher',
  noPublisher: 'None',
  categories: 'Categories',
  language: 'Language',
  genres: 'Genres (up to 3)',
  ageGroup: 'Age group',
  minAge: 'Minimum age (optional)',
  readingLevel: 'Reading level',
  synopsis: 'Synopsis',
  edition: 'Edition',
  year: 'Publication year',
  keywords: 'Keywords (comma separated)',
  contentTags: 'Content notes (comma separated)',
  replacementPrice: 'Replacement price (₹)',
  replacementHint: 'Charged against the deposit if a copy is lost. Leave 0 to use the copy’s cost.',
  filterList: 'Filter…',
  addNew: 'Add',
  authorsTab: 'Authors',
  publishersTab: 'Publishers',
  categoriesTab: 'Categories',
  refName: 'Name',
  refEmpty: 'None yet.',
  archiveBook: (t: string) => `Archive "${t}"?`,
  archiveBookBody: 'The title is hidden from discovery and new stock. Copies and history stay.',
  // book detail
  availability: 'Availability',
  availableOf: (a: number, t: number) => `${a} of ${t} on the shelf`,
  noStock: 'No copies in this organization yet.',
  stockNone: 'No copies at any branch',
  stockLoading: 'Checking branches…',
  stockAt: (branch: string, available: number, total: number) => `${branch}: ${available} of ${total} on the shelf`,
  copyElsewhere: (code: string, title: string, branch: string, status: string) => `${code} (${title}) is at ${branch} · ${status}.`,
  viewBook: 'See the book',
  copiesHere: 'Copies at this branch',
  addCopies: 'Add copies',
  printLabels: 'Print labels',
  quantity: 'Quantity',
  cost: 'Cost per copy (₹)',
  condition: 'Condition',
  location: 'Shelf location',
  noLocation: 'Not shelved yet',
  ownBarcodes: 'Existing barcodes (optional, one per line)',
  ownBarcodesHint: 'Leave empty to print new Stories labels (the barcode is the copy code).',
  added: (n: number) => `${n} cop${n === 1 ? 'y' : 'ies'} added.`,
  // inventory
  inventoryTitle: 'Inventory',
  allStatuses: 'All statuses',
  findCopy: 'Find a copy',
  copyNotFound: 'No copy with that barcode in this organization.',
  copiesEmpty: 'No copies here yet. Add copies from a book in the catalogue.',
  locations: 'Shelf locations',
  newLocation: 'New location',
  code: 'Code',
  labelText: 'Label',
  kind: 'Kind',
  copy: 'Copy',
  status: 'Status',
  loans: 'Loans',
  history: 'History',
  owner: 'Owning branch',
  currentlyAt: 'Currently at',
  inspect: 'Inspect',
  passInspection: 'Back on the shelf',
  failInspection: 'Damaged',
  repair: 'Repaired',
  relocate: 'Move',
  markLost: 'Mark lost',
  found: 'Found it',
  retire: 'Retire',
  recordCondition: 'Record condition',
  retireTitle: (c: string) => `Retire ${c}?`,
  retireBody: 'Retired copies never circulate again. The record and its history are kept.',
  lostTitle: (c: string) => `Mark ${c} as lost?`,
  lostBody: 'Use this for a copy missing from the shelf. For a book lost by a member, declare the loan lost from the member page.',
  note: 'Note (optional)',
  labelsTitle: 'Labels',
  labelsHint: 'Print on A4 label sheets (3 × 8). Use your browser’s print dialog.',
  print: 'Print',
  // members
  membersTitle: 'Members',
  searchMembers: 'Search by name, member code or mobile',
  registerMember: 'Register member',
  membersHint: 'Search to find a member at this branch.',
  membersEmpty: 'No members match at this branch.',
  membersNone: 'No members at this branch yet.',
  allMembers: 'All members',
  subscription: 'Subscription',
  subActive: 'Active subscription',
  subDue: (days: number) => `Renewal due in ${days} days`,
  subExpired: 'Expired',
  subNone: 'Never subscribed',
  noSubscription: 'No subscription',
  expiredAgo: (ago: string) => `ended ${ago}`,
  renewalDate: 'Renews / ended',
  clearFilters: 'Clear filters',
  fullName: 'Full name',
  dob: 'Date of birth',
  mobile: 'Mobile',
  mobileHint: 'Required for adults.',
  email: 'Email (optional)',
  guardian: 'Guardian',
  guardianHint: 'Under 18: search and choose the parent or guardian (register them first).',
  relationship: 'Relationship',
  addressOptional: 'Address (optional)',
  memberSince: 'Member code',
  books: 'Books',
  held: (n: number, max: number) => `${n} of ${max} held`,
  noPlan: 'No active plan',
  subscribe: 'Subscribe',
  renew: 'Renew',
  choosePlan: 'Choose a plan',
  amountDue: 'Amount due',
  planFee: 'Plan fee',
  depositTopUp: 'Security deposit',
  total: 'Total',
  recordPayment: 'Record payment',
  paymentMethod: 'Payment method',
  reference: 'Reference (UPI / card / bank)',
  pendingPayment: 'Waiting for payment',
  paymentRecorded: 'Payment recorded. The subscription is active.',
  cancelPending: 'Cancel',
  activeUntil: (d: string) => `Active until ${d}`,
  renewsOn: (d: string) => `Renewal starts ${d}`,
  exchangesThisTerm: (n: number) => `${n} exchange${n === 1 ? '' : 's'} this term`,
  lifetime: (loans: number, ex: number) => `${loans} books borrowed · ${ex} exchanges in total`,
  deposit: 'Security deposit',
  balance: 'Balance',
  proposeAdjustment: 'Propose adjustment',
  deduction: 'Deduction (damage, loss)',
  adjustment: 'Adjustment',
  credit: 'Credit',
  debit: 'Debit',
  amount: 'Amount (₹)',
  startSettlement: 'Start settlement',
  refund: 'Refund deposit',
  refundBody: (a: string) => `Refund ${a} and close the deposit account.`,
  ledgerEmpty: 'No deposit transactions yet.',
  currentBooks: 'Current books',
  noCurrentBooks: 'No books on loan.',
  borrowedFor: 'With the member',
  declareLost: 'Declare lost',
  declareLostTitle: (t: string) => `Declare "${t}" lost?`,
  declareLostBody: 'The loan closes, the member’s slot frees up and a deposit deduction is proposed for approval.',
  loanHistory: 'Borrowing history',
  reservations: 'Reservations',
  placeReservation: 'Reserve a title',
  noReservations: 'No reservations.',
  holdUntil: (d: string) => `Held until ${d}`,
  suspend: 'Suspend',
  reactivate: 'Reactivate',
  closeMembership: 'Close membership',
  statusTitle: (a: string) => `${a}?`,
  wards: 'Children',
  pendingApprovals: 'Pending approval',
  // plans
  plansTitle: 'Subscription plans',
  newPlan: 'New plan',
  editPlan: 'Edit plan (creates a new version)',
  planName: 'Plan name',
  description: 'Description',
  duration: 'Duration',
  price: 'Price (₹)',
  depositAmount: 'Security deposit (₹)',
  maxBooks: 'Books at a time',
  audiences: 'Who can buy it',
  deliveryEligible: 'Home delivery available',
  promo: 'Promotional price',
  promoPrice: 'Promo price (₹)',
  promoFrom: 'From',
  promoTo: 'To',
  renewalWindow: 'Renewal opens (days before expiry)',
  plansEmpty: 'No plans yet. Create the first one.',
  version: (v: number) => `v${v}`,
  archivePlan: (n: string) => `Stop selling ${n}?`,
  archivePlanBody: 'Members on this plan keep their terms until they expire.',
  // deposits approvals
  approvalsTitle: 'Deposit approvals',
  approvalsEmpty: 'Nothing waiting for approval.',
  approve: 'Approve',
  reject: 'Reject',
  proposedBy: 'Proposed by',
  // desk
  deskTitle: 'Circulation desk',
  findMember: 'Member',
  findMemberHint: 'Scan the member card or search by name, code or mobile',
  changeMember: 'Change member',
  toReturn: 'Returning',
  toIssue: 'Issuing',
  scanToIssue: 'Scan a book to issue',
  quickReturn: 'Quick return (no member needed)',
  scanToReturn: 'Scan a returned book',
  returned: (n: number) => `${n} book${n === 1 ? '' : 's'} returned. Put them in the inspection tray.`,
  issueN: (n: number) => `Issue ${n} book${n === 1 ? '' : 's'}`,
  returnN: (n: number) => `Return ${n} book${n === 1 ? '' : 's'}`,
  exchangeN: (r: number, i: number) => `Exchange: return ${r}, issue ${i}`,
  done: 'Done.',
  nothingStaged: 'Tick books to return or scan books to issue',
  alreadyStaged: 'Already in the list.',
  onLoanElsewhere: 'That copy is on loan — use Return instead.',
  notOnShelf: (s: string) => `That copy is ${s.toLowerCase().replace('_', ' ')} and can't be issued.`,
  cantBorrow: 'Can’t borrow',
  inspections: 'Waiting for inspection',
  noInspections: 'Nothing waiting for inspection.',
  deskModeMember: 'Member desk',
  deskModeReturn: 'Quick return',
  deskModeInspect: 'Inspection',
  // reservations
  reservationsTitle: 'Reservations',
  awaitingPickup: 'Ready for pickup',
  waitingQueue: 'Waiting',
  reserveFor: 'Member',
  reserveBook: 'Book',
  searchTitle: 'Search the catalogue',
  cancelReservation: 'Cancel reservation',
  // transfers
  transfersTitle: 'Transfers',
  outgoing: 'Outgoing',
  incoming: 'Incoming',
  newTransfer: 'New transfer',
  toBranch: 'To branch',
  dispatch: 'Dispatch',
  receive: 'Receive',
  transfersEmpty: 'No transfers.',
  items: 'Copies',
  damaged: 'Damaged',
  staged: 'Scanned',
  // dashboard
  issuedToday: 'Issued today',
  exchangesToday: 'Exchanges today',
  awaitingInspection: 'Awaiting inspection',
  holdsReady: 'Holds ready for pickup',
  waitingReservations: 'Members waiting',
  incomingTransfers: 'Incoming transfers',
  approvalsPending: 'Deposit approvals',

  // numbering
  numbering: 'Numbering',
  numberingTitle: (branch: string) => `Numbering at ${branch}`,
  numberingIntro:
    'Patterns for the codes this branch creates. Only new records use a changed pattern — existing codes and printed labels stay as they are.',
  numberingCopy: 'Book copies',
  numberingMember: 'Members',
  numberingLocation: 'Shelves (when no code is typed)',
  numberingEmployee: 'Employee IDs',
  numberingBook: 'Book codes',
  numberingBookTitle: 'Book numbering',
  numberingBookIntro: 'Codes for new catalogue titles, shared by every organization. Existing titles keep their codes.',
  numberingExample: (codes: string) => `Next codes look like ${codes}`,
  numberingDefault: 'Default:',
  numberingTokens: 'What can go in a pattern?',
  employeeId: 'Employee ID',
  employeeIdHint: 'Leave blank to number automatically with the branch pattern.',
  locationCodeAuto: 'Leave blank to number it automatically.',

  // covers
  coverAdd: 'Add cover',
  coverChange: 'Change cover',
  coverRemove: 'Remove',
  coverSaving: 'Uploading…',
  coverChoose: 'Choose a cover image',
  coverNotImage: 'Choose a photo or image file (JPEG, PNG or WebP).',
  coverUnreadable: "This image couldn't be read. Try a JPEG or PNG.",
  coverFailed: "The cover couldn't be saved. Try again.",

  // member history & audit trail
  tabOverview: 'Overview',
  tabHistory: 'History',
  tabAudit: 'Audit trail',
  subscriptionHistory: 'Subscriptions',
  paymentHistory: 'Payments',
  noSubscriptions: 'No subscriptions yet.',
  noPayments: 'No payments recorded.',
  noLoanHistory: 'No returned books yet.',
  noActivity: 'Nothing recorded for this member yet.',
  plan: 'Plan',
  period: 'Period',
  amountCol: 'Amount',
  date: 'Date',
  paidFor: 'For',
  method: 'Method',
  renewal: 'Renewal',
  newSubscription: 'New',
  actRegistered: 'Registered as a member',
  actUpdated: 'Details updated',
  actStatus: (s: string) => `Membership ${s.toLowerCase()}`,
  actSubscribed: (amount: string) => `Subscription created (${amount} due)`,
  actSubCancelled: 'Unpaid subscription cancelled',
  actSubExpired: 'Subscription expired',
  actPaid: (amount: string, method: string, until: string) => `Paid ${amount} (${method}) · active until ${until}`,
  actIssued: (what: string) => `Borrowed ${what}`,
  actReturned: (what: string) => `Returned ${what}`,
  actExchanged: (back: string, out: string) => `Exchanged ${back} for ${out}`,
  actLost: 'Book declared lost',
  actReserved: 'Reserved a title',
  actReservationCancelled: 'Reservation cancelled',
  actReservationExpired: 'Reservation hold expired',
  actDepositProposed: (amount: string) => `Deposit adjustment of ${amount} proposed`,
  actDepositApproved: 'Deposit adjustment approved',
  actDepositRejected: 'Deposit adjustment rejected',
  actSettlement: 'Deposit settlement started',
  actRefunded: 'Deposit refunded',

  // book details lookup
  lookupTitle: 'Find book details',
  lookupPlaceholder: 'Find book details: title, "title author", or ISBN',
  lookupButton: 'Search',
  lookupSearching: 'Searching…',
  lookupHint: 'Searches Google Books and Open Library. Pick a match to fill the form, then check the details before saving.',
  lookupNone: 'No matches. Try the ISBN, a shorter title, or add the author\'s name.',
  lookupNoAuthor: 'Author unknown',
  lookupUse: 'Use this',
  lookupApplying: 'Filling…',
  lookupExisting: 'Already in catalogue',
  lookupFailed: "Book search didn't work. Fill in the details by hand.",
  lookupCoverNote: (source: string) => `The cover from ${source} will be added when you save.`,
  lookupCoverSkip: "Don't use this cover",

  // online payments (Razorpay)
  payments: 'Payments',
  copyText: 'Copy',
  copied: 'Copied',
  close: 'Close',
  finished: 'Done',
  pgTitle: (branch: string) => `Online payments at ${branch}`,
  pgIntro: 'Collect subscription payments with Razorpay: a payment link sent to the member by SMS and email, or a UPI QR code at the counter. Keys are in the Razorpay Dashboard → Account & Settings → API Keys.',
  pgEnabled: 'Accept online payments at this branch',
  pgKeyId: 'Key ID',
  pgKeyIdHint: 'Starts with rzp_test_ (testing) or rzp_live_ (real payments).',
  pgLive: 'Live key: members will be charged real money.',
  pgKeySecret: 'Key secret',
  pgWebhookSecret: 'Webhook secret',
  pgSecretSaved: 'Saved. Leave blank to keep it.',
  pgSecretNeeded: 'Enter the key secret for this key ID.',
  pgWebhookSecretHint: 'The secret you type when creating the webhook in Razorpay (step 3 below).',
  pgSendLinkBy: 'Razorpay sends payment links by',
  pgSms: 'SMS to the member\'s mobile',
  pgEmail: 'Email (when the member has one)',
  pgWebhookTitle: 'Confirm payments automatically (webhook)',
  pgWebhookStep1: 'In the Razorpay Dashboard open Account & Settings → Webhooks → Add new webhook.',
  pgWebhookStep2: 'Webhook URL:',
  pgWebhookUrl: 'Webhook URL',
  pgWebhookStep3: 'Choose a secret, type it here as the webhook secret, and tick the events payment_link.paid and qr_code.credited.',
  pgWebhookStep4: 'Without a webhook, staff press "Check payment status" after the member pays.',
  pgTest: 'Test connection',
  pgTestOk: (mode: string) => `Connected to Razorpay (${mode} mode).`,
  pgTestFailed: "Couldn't reach Razorpay.",
  collectOnline: 'Collect online',
  olTitle: 'Collect online',
  olLink: 'Send payment link',
  olLinkHint: (to: string) => `By SMS and email to ${to}. The member pays with UPI, card or net banking.`,
  olNoContact: 'Add a mobile number or email to the member first.',
  olQr: 'Show UPI QR code',
  olQrHint: 'The member scans it with any UPI app (GPay, PhonePe, Paytm…) at the counter.',
  olCreating: 'Creating…',
  olSent: (to: string) => `Payment link sent to ${to}.`,
  olLinkReady: 'Payment link ready. Share it with the member.',
  olQrAlt: 'UPI QR code for this payment',
  olScanUpi: 'Scan with any UPI app to pay the exact amount.',
  olScanLink: 'Scan with the phone camera or a UPI app to open the payment page.',
  olWaiting: 'Waiting for the payment. This updates by itself.',
  olExpires: (at: string) => `expires ${at}`,
  olCheck: 'Check payment status',
  olChecking: 'Checking…',
  olNotYet: 'Not paid yet.',
  olCancel: 'Cancel request',
  olCancelling: 'Cancelling…',
  olPaid: 'Payment received. The subscription is active.',
  olAttention: (why: string) => `Payment received but not applied: ${why} Finance will refund or apply it.`,
  olClosed: (status: string) => `This request is ${status}.`,
  olTestMode: 'Test mode: no real money',
  actOnlineRequested: (how: string) => `Online payment requested (${how})`,
  actOnlineCancelled: 'Online payment request cancelled',
  actOnlineUnapplied: (amount: string) => `Online payment of ${amount} received but not applied`,

  // camera barcode scanning
  camUse: 'Scan with the camera',
  camScanIsbn: 'Scan the ISBN barcode with the camera',
  camTitle: 'Camera',
  camPreview: 'Camera preview',
  camStarting: 'Starting the camera…',
  camHint: 'Hold the label\'s QR code inside the frame, 20–30 cm from the camera so it looks sharp. Labels without a QR code: print new ones from Inventory → Print labels.',
  camScanned: (code: string) => `Scanned ${code}`,
  camChoose: 'Choose camera',
  camDefault: 'Default camera',
  camStop: 'Stop camera',
  camDenied: 'Camera access is blocked. Click the camera icon in the address bar, allow the camera for this site, and try again.',
  camNone: 'No camera found on this device.',
  camBusy: 'The camera is in use by another app (e.g. a video call). Close it and try again.',
  camInsecure: 'The camera only works on the secure (https) site.',
  camFailed: "The camera couldn't be started.",
};
