// User-facing copy for the Phase 1 library screens (kept out of components for i18n).
export const lt = {
  // catalogue
  catalogueTitle: 'Catalogue',
  searchBooks: 'Search by title, author, ISBN or code',
  allAges: 'All ages',
  newBook: 'New book',
  editBook: 'Edit book',
  referenceData: 'Authors, publishers & categories',
  booksEmpty: 'No books match.',
  booksEmptyHint: 'Try a shorter search, or add the title to the catalogue.',
  title: 'Title',
  subtitle: 'Subtitle (optional)',
  isbn: 'ISBN (optional)',
  isbnHint: 'ISBN-10 or ISBN-13; hyphens are fine.',
  authors: 'Authors',
  publisher: 'Publisher',
  noPublisher: 'None',
  categories: 'Categories',
  language: 'Language',
  genres: 'Genres (up to 3)',
  ageGroup: 'Age group',
  minAge: 'Minimum age (optional)',
  readingLevel: 'Reading level',
  synopsis: 'Synopsis',
  edition: 'Edition',
  year: 'Publication year',
  keywords: 'Keywords (comma separated)',
  contentTags: 'Content notes (comma separated)',
  replacementPrice: 'Replacement price (₹)',
  replacementHint: 'Charged against the deposit if a copy is lost. Leave 0 to use the copy’s cost.',
  filterList: 'Filter…',
  addNew: 'Add',
  authorsTab: 'Authors',
  publishersTab: 'Publishers',
  categoriesTab: 'Categories',
  refName: 'Name',
  refEmpty: 'None yet.',
  archiveBook: (t: string) => `Archive "${t}"?`,
  archiveBookBody: 'The title is hidden from discovery and new stock. Copies and history stay.',
  // book detail
  availability: 'Availability',
  availableOf: (a: number, t: number) => `${a} of ${t} on the shelf`,
  noStock: 'No copies in this organization yet.',
  copiesHere: 'Copies at this branch',
  addCopies: 'Add copies',
  printLabels: 'Print labels',
  quantity: 'Quantity',
  cost: 'Cost per copy (₹)',
  condition: 'Condition',
  location: 'Shelf location',
  noLocation: 'Not shelved yet',
  ownBarcodes: 'Existing barcodes (optional, one per line)',
  ownBarcodesHint: 'Leave empty to print new Stories labels (the barcode is the copy code).',
  added: (n: number) => `${n} cop${n === 1 ? 'y' : 'ies'} added.`,
  // inventory
  inventoryTitle: 'Inventory',
  allStatuses: 'All statuses',
  findCopy: 'Find a copy',
  copyNotFound: 'No copy with that barcode at this branch.',
  copiesEmpty: 'No copies here yet. Add copies from a book in the catalogue.',
  locations: 'Shelf locations',
  newLocation: 'New location',
  code: 'Code',
  labelText: 'Label',
  kind: 'Kind',
  copy: 'Copy',
  status: 'Status',
  loans: 'Loans',
  history: 'History',
  owner: 'Owning branch',
  currentlyAt: 'Currently at',
  inspect: 'Inspect',
  passInspection: 'Back on the shelf',
  failInspection: 'Damaged',
  repair: 'Repaired',
  relocate: 'Move',
  markLost: 'Mark lost',
  found: 'Found it',
  retire: 'Retire',
  recordCondition: 'Record condition',
  retireTitle: (c: string) => `Retire ${c}?`,
  retireBody: 'Retired copies never circulate again. The record and its history are kept.',
  lostTitle: (c: string) => `Mark ${c} as lost?`,
  lostBody: 'Use this for a copy missing from the shelf. For a book lost by a member, declare the loan lost from the member page.',
  note: 'Note (optional)',
  labelsTitle: 'Labels',
  labelsHint: 'Print on A4 label sheets (3 × 8). Use your browser’s print dialog.',
  print: 'Print',
  // members
  membersTitle: 'Members',
  searchMembers: 'Search by name, member code or mobile',
  registerMember: 'Register member',
  membersHint: 'Search to find a member at this branch.',
  membersEmpty: 'No members match at this branch.',
  fullName: 'Full name',
  dob: 'Date of birth',
  mobile: 'Mobile',
  mobileHint: 'Required for adults.',
  email: 'Email (optional)',
  guardian: 'Guardian',
  guardianHint: 'Under 18: search and choose the parent or guardian (register them first).',
  relationship: 'Relationship',
  addressOptional: 'Address (optional)',
  memberSince: 'Member code',
  books: 'Books',
  held: (n: number, max: number) => `${n} of ${max} held`,
  noPlan: 'No active plan',
  subscription: 'Subscription',
  subscribe: 'Subscribe',
  renew: 'Renew',
  choosePlan: 'Choose a plan',
  amountDue: 'Amount due',
  planFee: 'Plan fee',
  depositTopUp: 'Security deposit',
  total: 'Total',
  recordPayment: 'Record payment',
  paymentMethod: 'Payment method',
  reference: 'Reference (UPI / card / bank)',
  pendingPayment: 'Waiting for payment',
  paymentRecorded: 'Payment recorded. The subscription is active.',
  cancelPending: 'Cancel',
  activeUntil: (d: string) => `Active until ${d}`,
  renewsOn: (d: string) => `Renewal starts ${d}`,
  exchangesThisTerm: (n: number) => `${n} exchange${n === 1 ? '' : 's'} this term`,
  lifetime: (loans: number, ex: number) => `${loans} books borrowed · ${ex} exchanges in total`,
  deposit: 'Security deposit',
  balance: 'Balance',
  proposeAdjustment: 'Propose adjustment',
  deduction: 'Deduction (damage, loss)',
  adjustment: 'Adjustment',
  credit: 'Credit',
  debit: 'Debit',
  amount: 'Amount (₹)',
  startSettlement: 'Start settlement',
  refund: 'Refund deposit',
  refundBody: (a: string) => `Refund ${a} and close the deposit account.`,
  ledgerEmpty: 'No deposit transactions yet.',
  currentBooks: 'Current books',
  noCurrentBooks: 'No books on loan.',
  borrowedFor: 'With the member',
  declareLost: 'Declare lost',
  declareLostTitle: (t: string) => `Declare "${t}" lost?`,
  declareLostBody: 'The loan closes, the member’s slot frees up and a deposit deduction is proposed for approval.',
  loanHistory: 'History',
  reservations: 'Reservations',
  placeReservation: 'Reserve a title',
  noReservations: 'No reservations.',
  holdUntil: (d: string) => `Held until ${d}`,
  suspend: 'Suspend',
  reactivate: 'Reactivate',
  closeMembership: 'Close membership',
  statusTitle: (a: string) => `${a}?`,
  wards: 'Children',
  pendingApprovals: 'Pending approval',
  // plans
  plansTitle: 'Subscription plans',
  newPlan: 'New plan',
  editPlan: 'Edit plan (creates a new version)',
  planName: 'Plan name',
  description: 'Description',
  duration: 'Duration',
  price: 'Price (₹)',
  depositAmount: 'Security deposit (₹)',
  maxBooks: 'Books at a time',
  audiences: 'Who can buy it',
  deliveryEligible: 'Home delivery available',
  promo: 'Promotional price',
  promoPrice: 'Promo price (₹)',
  promoFrom: 'From',
  promoTo: 'To',
  renewalWindow: 'Renewal opens (days before expiry)',
  plansEmpty: 'No plans yet. Create the first one.',
  version: (v: number) => `v${v}`,
  archivePlan: (n: string) => `Stop selling ${n}?`,
  archivePlanBody: 'Members on this plan keep their terms until they expire.',
  // deposits approvals
  approvalsTitle: 'Deposit approvals',
  approvalsEmpty: 'Nothing waiting for approval.',
  approve: 'Approve',
  reject: 'Reject',
  proposedBy: 'Proposed by',
  // desk
  deskTitle: 'Circulation desk',
  findMember: 'Member',
  findMemberHint: 'Scan the member card or search by name, code or mobile',
  changeMember: 'Change member',
  toReturn: 'Returning',
  toIssue: 'Issuing',
  scanToIssue: 'Scan a book to issue',
  quickReturn: 'Quick return (no member needed)',
  scanToReturn: 'Scan a returned book',
  returned: (n: number) => `${n} book${n === 1 ? '' : 's'} returned. Put them in the inspection tray.`,
  issueN: (n: number) => `Issue ${n} book${n === 1 ? '' : 's'}`,
  returnN: (n: number) => `Return ${n} book${n === 1 ? '' : 's'}`,
  exchangeN: (r: number, i: number) => `Exchange: return ${r}, issue ${i}`,
  done: 'Done.',
  nothingStaged: 'Tick books to return or scan books to issue',
  alreadyStaged: 'Already in the list.',
  onLoanElsewhere: 'That copy is on loan — use Return instead.',
  notOnShelf: (s: string) => `That copy is ${s.toLowerCase().replace('_', ' ')} and can't be issued.`,
  cantBorrow: 'Can’t borrow',
  inspections: 'Waiting for inspection',
  noInspections: 'Nothing waiting for inspection.',
  deskModeMember: 'Member desk',
  deskModeReturn: 'Quick return',
  deskModeInspect: 'Inspection',
  // reservations
  reservationsTitle: 'Reservations',
  awaitingPickup: 'Ready for pickup',
  waitingQueue: 'Waiting',
  reserveFor: 'Member',
  reserveBook: 'Book',
  searchTitle: 'Search the catalogue',
  cancelReservation: 'Cancel reservation',
  // transfers
  transfersTitle: 'Transfers',
  outgoing: 'Outgoing',
  incoming: 'Incoming',
  newTransfer: 'New transfer',
  toBranch: 'To branch',
  dispatch: 'Dispatch',
  receive: 'Receive',
  transfersEmpty: 'No transfers.',
  items: 'Copies',
  damaged: 'Damaged',
  staged: 'Scanned',
  // dashboard
  issuedToday: 'Issued today',
  exchangesToday: 'Exchanges today',
  awaitingInspection: 'Awaiting inspection',
  holdsReady: 'Holds ready for pickup',
  waitingReservations: 'Members waiting',
  incomingTransfers: 'Incoming transfers',
  approvalsPending: 'Deposit approvals',

  // numbering
  numbering: 'Numbering',
  numberingTitle: (branch: string) => `Numbering at ${branch}`,
  numberingIntro:
    'Patterns for the codes this branch creates. Only new records use a changed pattern — existing codes and printed labels stay as they are.',
  numberingCopy: 'Book copies',
  numberingMember: 'Members',
  numberingLocation: 'Shelves (when no code is typed)',
  numberingEmployee: 'Employee IDs',
  numberingBook: 'Book codes',
  numberingBookTitle: 'Book numbering',
  numberingBookIntro: 'Codes for new catalogue titles, shared by every organization. Existing titles keep their codes.',
  numberingExample: (codes: string) => `Next codes look like ${codes}`,
  numberingDefault: 'Default:',
  numberingTokens: 'What can go in a pattern?',
  employeeId: 'Employee ID',
  employeeIdHint: 'Leave blank to number automatically with the branch pattern.',
  locationCodeAuto: 'Leave blank to number it automatically.',
};
