import type { AuthFailureCode } from './auth/models';

// All user-facing copy lives here so it can move to an i18n library unchanged.
export const t = {
  appTitle: 'Stories',
  tagline: 'Every book begins a new story.',
  signInTitle: 'Welcome back',
  signInSubtitle: 'Sign in to borrow, exchange and discover your next book.',
  emailLabel: 'Email',
  passwordLabel: 'Password',
  signInButton: 'Sign in',
  createAccountButton: 'Create an account',
  haveAccountButton: 'I already have an account',
  createAccountTitle: 'Join Stories',
  createAccountSubtitle: "Create your account. You'll choose a subscription next.",
  fullNameLabel: 'Full name',
  continueWithGoogle: 'Continue with Google',
  forgotPassword: 'Forgot password?',
  resetEmailSent: (email: string) => `If an account exists for ${email}, a reset link is on its way.`,
  orDivider: 'or',
  validationEmail: 'Enter a valid email address.',
  validationPassword: 'Use at least 8 characters.',
  validationName: 'Enter your name.',
  navHome: 'Home',
  navExplore: 'Explore',
  navMyBooks: 'My Books',
  navOrders: 'Orders',
  navProfile: 'Profile',
  greeting: (name: string) => `Hello, ${name}`,
  greetingFallback: 'Hello, reader',
  noMembershipTitle: 'No active membership yet',
  noMembershipMessage:
    'Subscriptions open soon. Once you subscribe you can borrow within your plan and exchange books as often as you like.',
  exploreEmptyTitle: 'The catalogue is on its way',
  exploreEmptyMessage: 'Our librarians are adding books. Check back soon to browse by age, genre and language.',
  myBooksEmptyTitle: 'No books currently borrowed',
  myBooksEmptyMessage: 'Books you borrow, reserve or add to your wishlist will appear here.',
  ordersEmptyTitle: 'No upcoming deliveries',
  ordersEmptyMessage: 'Home deliveries, return pickups and exchanges will appear here.',
  profileSignedInAs: (email: string) => `Signed in as ${email}`,
  signOut: 'Sign out',
  loading: 'Loading…',

  // Shared
  errorGeneric: 'Something went wrong on our side. Please try again.',
  errorNetwork: 'You appear to be offline. Check your connection and try again.',
  errorLoad: "We couldn't load this. Check your connection and try again.",
  errorIndex: 'This list is still being set up on the server (a database index is building). Try again in a few minutes; if it persists, run the backend deploy again.',
  errorForbidden: "You don't have permission to see this.",
  retry: 'Try again',
  cancel: 'Cancel',
  save: 'Save',
  saving: 'Saving…',
  create: 'Create',
  edit: 'Edit',
  archive: 'Archive',
  close: 'Close',
  required: 'Required',
  reasonLabel: 'Reason',
  reasonHint: 'Recorded in the audit log.',
  allBranches: 'All branches',
  active: 'Active',
  archived: 'Archived',
  revoked: 'Revoked',
  suspended: 'Suspended',
  notFoundTitle: 'Page not found',
  noAccessTitle: "You don't have access to this page",
  noAccessMessage: 'Ask an administrator if you think you should.',

  // Staff console
  consoleTitle: 'Stories Console',
  memberView: 'Member view',
  staffConsole: 'Staff console',
  organization: 'Organization',
  branch: 'Branch',
  navDashboard: 'Dashboard',
  navOrganizations: 'Organizations',
  navBranches: 'Branches',
  navDepartments: 'Departments',
  navStaff: 'Staff & roles',
  navAudit: 'Audit log',
  sectionLibrary: 'Library',
  sectionMembers: 'Members',
  sectionOrganization: 'Organization',
  navDesk: 'Circulation desk',
  navCatalogue: 'Catalogue',
  navInventory: 'Inventory',
  navReservations: 'Reservations',
  navTransfers: 'Transfers',
  navMembers: 'Members',
  navPlans: 'Subscription plans',
  navDepositApprovals: 'Deposit approvals',
  filterPlaceholder: 'Filter…',
  scanPlaceholder: 'Scan or type a barcode',
  scanAdd: 'Add',
  noBranchTitle: 'No branch to work at',
  noBranchMessage: 'You need a role at an active branch to use this page.',
  noOrgTitle: 'No organization yet',
  noOrgMessage: 'Create the first organization to start setting up Stories.',

  dashboardTitle: 'What needs doing',
  dashboardAllClear: 'Nothing needs your attention right now.',
  todoCreateOrg: 'Create your first organization',
  todoCreateBranch: 'Add a branch to this organization',
  todoAddStaff: 'Give your team their roles',
  todoVerifyEmail: 'Verify your email address',

  orgsTitle: 'Organizations',
  orgNew: 'New organization',
  orgName: 'Organization name',
  orgType: 'Type',
  orgCorporate: 'Corporate (company owned)',
  orgFranchise: 'Franchise',
  orgsEmpty: 'No organizations yet.',

  branchesTitle: 'Branches',
  branchNew: 'New branch',
  branchEdit: 'Edit branch',
  branchCode: 'Branch code',
  branchCodeHint: '2–8 letters or digits, e.g. CEN. Cannot be changed later.',
  branchName: 'Branch name',
  addressLine1: 'Address line 1',
  addressLine2: 'Address line 2 (optional)',
  city: 'City',
  state: 'State',
  postalCode: 'PIN code',
  phone: 'Phone',
  contactEmail: 'Email (optional)',
  hoursTitle: 'Opening hours',
  closedDay: 'Closed',
  branchesEmpty: 'No branches yet.',
  branchArchiveTitle: (name: string) => `Archive ${name}?`,
  branchArchiveBody: 'The branch stays in history and reports but can no longer be edited or used.',
  companyOwned: 'Company owned',
  franchise: 'Franchise',

  departmentsTitle: 'Departments',
  departmentNew: 'New department',
  departmentName: 'Department name',
  departmentScope: 'Applies to',
  departmentsEmpty: 'No departments yet.',
  departmentArchiveTitle: (name: string) => `Archive ${name}?`,
  rename: 'Rename',

  staffTitle: 'Staff & roles',
  staffAdd: 'Add staff member',
  staffEditRoles: 'Edit roles',
  staffEmail: 'Email address',
  staffEmailHint: 'The person must have signed up to Stories with this email.',
  staffRoles: 'Roles',
  staffBranches: 'Branches',
  staffRevoke: 'Remove roles',
  staffRevokeTitle: (name: string) => `Remove all roles for ${name}?`,
  staffRevokeBody: 'They keep their Stories account but lose staff access in this organization.',
  staffEmpty: 'No staff yet. Add the first team member.',
  staffYou: 'You',

  auditTitle: 'Audit log',
  auditEmpty: 'No activity recorded yet.',
  auditWhen: 'When',
  auditAction: 'Action',
  auditEntity: 'Record',
  auditActor: 'By',
  auditDetails: 'Details',
  auditSystem: 'System (automatic)',
  loadMore: 'Load more',

  setupTitle: 'Set up administration',
  setupBody: 'The owner account can claim the first Super Admin role once. Other people get their roles from an administrator.',
  setupClaim: 'Become Super Admin',
  setupDone: "You're now the Super Admin.",
  setupOpenConsole: 'Open the staff console',
  verifyTitle: 'Verify your email first',
  verifyBody: (email: string) => `We sent a verification link to ${email}. Open it, then come back here.`,
  verifyResend: 'Send the link again',
  verifySent: 'Verification email sent.',
  verifyDone: "I've verified it",
} as const;

export const authErrorMessage: Record<AuthFailureCode, string> = {
  invalidCredentials: "That email and password don't match. Check them and try again, or reset your password.",
  emailInUse: 'An account already exists for this email. Sign in instead.',
  weakPassword: 'Choose a stronger password with at least 8 characters.',
  tooManyRequests: 'Too many attempts. Wait a few minutes, then try again.',
  network: 'You appear to be offline. Check your connection and try again.',
  popupClosed: 'Google sign-in was cancelled.',
  userDisabled: 'This account has been disabled. Please contact Stories support.',
  providerDisabled: "This sign-in method isn't switched on yet. Please contact Stories support.",
  popupBlocked: 'Your browser blocked the Google sign-in window. Allow pop-ups for this site and try again.',
  unauthorizedDomain: "Sign-in isn't allowed from this web address yet. Please contact Stories support.",
  unknown: 'Please try again. If it keeps happening, contact your branch.',
};
