import type { AuthFailureCode } from './auth/models';

// All user-facing copy lives here so it can move to an i18n library unchanged.
export const t = {
  appTitle: 'Stories',
  tagline: 'Every book begins a new story.',
  signInTitle: 'Welcome back',
  signInSubtitle: 'Sign in to borrow, exchange and discover your next book.',
  emailLabel: 'Email',
  passwordLabel: 'Password',
  signInButton: 'Sign in',
  createAccountButton: 'Create an account',
  haveAccountButton: 'I already have an account',
  createAccountTitle: 'Join Stories',
  createAccountSubtitle: "Create your account. You'll choose a subscription next.",
  fullNameLabel: 'Full name',
  continueWithGoogle: 'Continue with Google',
  forgotPassword: 'Forgot password?',
  resetEmailSent: (email: string) => `If an account exists for ${email}, a reset link is on its way.`,
  orDivider: 'or',
  validationEmail: 'Enter a valid email address.',
  validationPassword: 'Use at least 8 characters.',
  validationName: 'Enter your name.',
  navHome: 'Home',
  navExplore: 'Explore',
  navMyBooks: 'My Books',
  navOrders: 'Orders',
  navProfile: 'Profile',
  greeting: (name: string) => `Hello, ${name}`,
  greetingFallback: 'Hello, reader',
  noMembershipTitle: 'No active membership yet',
  noMembershipMessage:
    'Subscriptions open soon. Once you subscribe you can borrow within your plan and exchange books as often as you like.',
  exploreEmptyTitle: 'The catalogue is on its way',
  exploreEmptyMessage: 'Our librarians are adding books. Check back soon to browse by age, genre and language.',
  myBooksEmptyTitle: 'No books currently borrowed',
  myBooksEmptyMessage: 'Books you borrow, reserve or add to your wishlist will appear here.',
  ordersEmptyTitle: 'No upcoming deliveries',
  ordersEmptyMessage: 'Home deliveries, return pickups and exchanges will appear here.',
  profileSignedInAs: (email: string) => `Signed in as ${email}`,
  signOut: 'Sign out',
  loading: 'Loading…',
} as const;

export const authErrorMessage: Record<AuthFailureCode, string> = {
  invalidCredentials: "That email and password don't match. Check them and try again, or reset your password.",
  emailInUse: 'An account already exists for this email. Sign in instead.',
  weakPassword: 'Choose a stronger password with at least 8 characters.',
  tooManyRequests: 'Too many attempts. Wait a few minutes, then try again.',
  network: 'You appear to be offline. Check your connection and try again.',
  popupClosed: 'Google sign-in was cancelled.',
  userDisabled: 'This account has been disabled. Please contact Stories support.',
  providerDisabled: "This sign-in method isn't switched on yet. Please contact Stories support.",
  popupBlocked: 'Your browser blocked the Google sign-in window. Allow pop-ups for this site and try again.',
  unauthorizedDomain: "Sign-in isn't allowed from this web address yet. Please contact Stories support.",
  unknown: 'Please try again. If it keeps happening, contact your branch.',
};
