/** Staff console strings for People (HRMS). */
export const ht = {
  sectionPeople: 'People',
  navEmployees: 'Employees',
  navHrSettings: 'HR settings',

  employeesTitle: 'Employees',
  employeesIntro: 'Everyone who works here: their job, status and records. Roles and system access are on each profile.',
  addEmployee: 'Add employee',
  searchEmployees: 'Search by name, ID or email',
  allStatuses: 'All statuses',
  allBranchesFilter: 'All branches',
  allDepartments: 'All departments',
  headOffice: 'Head office',
  noEmployees: 'No employees match.',
  noEmployeesYet: 'No employee records yet.',
  backfillTitle: (n: number) => `${n} staff member${n === 1 ? ' has' : 's have'} roles but no employee record`,
  backfillBody: 'They were added before People existed. Create their records now; their employee IDs are kept.',
  backfillAction: 'Create records',
  backfillDone: (created: number, linked: number) => `Created ${created} record${created === 1 ? '' : 's'}${linked ? `, linked ${linked}` : ''}.`,

  colName: 'Name',
  colDesignation: 'Designation',
  colBranch: 'Branch',
  colStatus: 'Status',
  colJoined: 'Joined',

  status: {
    DRAFT: 'Draft',
    ONBOARDING: 'Onboarding',
    ACTIVE: 'Active',
    NOTICE_PERIOD: 'Notice period',
    OFFBOARDING: 'Offboarding',
    OFFBOARDED: 'Offboarded',
  } as Record<string, string>,
  employmentType: { FULL_TIME: 'Full time', PART_TIME: 'Part time', CONTRACT: 'Contract', INTERN: 'Intern' } as Record<string, string>,

  fullName: 'Full name',
  workEmail: 'Email',
  workEmailHint: 'If the person has a Stories account with this email, it is linked now.',
  linkedEmailHint: 'Linked to a Stories account; the email comes from the account.',
  phone: 'Phone',
  branch: 'Branch',
  department: 'Department',
  designation: 'Designation',
  none: 'None',
  manager: 'Reports to',
  employmentTypeLabel: 'Employment type',
  joiningDate: 'Joining date',
  effectiveDate: 'Effective from',
  effectiveHint: 'For job changes. Recorded in the history.',
  changeNote: 'Note (optional)',
  employeeIdHint: 'Leave blank to number automatically with the branch pattern.',

  tabOverview: 'Overview',
  tabPersonal: 'Personal',
  tabBank: 'Bank',
  tabLifecycle: 'Onboarding & exit',
  tabHistory: 'History',
  tabAccess: 'Access',

  job: 'Job',
  contact: 'Contact',
  editDetails: 'Edit details',
  notSet: 'Not set',

  // Personal
  personalTitle: 'Personal and statutory details',
  editPersonal: 'Edit personal details',
  dob: 'Date of birth',
  gender: 'Gender',
  genders: { '': 'Not given', FEMALE: 'Female', MALE: 'Male', OTHER: 'Other' } as Record<string, string>,
  bloodGroup: 'Blood group',
  personalEmail: 'Personal email',
  personalPhone: 'Personal phone',
  currentAddress: 'Current address',
  permanentAddress: 'Permanent address',
  emergency: 'Emergency contact',
  emergencyName: 'Emergency contact name',
  emergencyRelation: 'Relationship',
  emergencyPhone: 'Emergency contact phone',
  pan: 'PAN',
  uan: 'UAN (PF)',
  esiNumber: 'ESI number',
  noPrivateAccess: 'Personal details are visible to HR and finance only.',

  // Bank
  bankTitle: 'Salary account',
  bankNone: 'No bank account recorded yet.',
  bankEdit: 'Change bank account',
  bankAdd: 'Add bank account',
  accountHolder: 'Account holder',
  accountNumber: 'Account number',
  bankName: 'Bank',
  ifsc: 'IFSC',
  reveal: 'Show full number',
  revealNote: 'Showing the full number is recorded in the audit log.',
  hide: 'Hide',
  masked: (last4: string) => `•••• •••• ${last4}`,

  // Lifecycle
  steps: {
    START_ONBOARDING: 'Start onboarding',
    ACTIVATE: 'Mark as joined',
    RESIGN: 'Record resignation',
    WITHDRAW_RESIGNATION: 'Withdraw resignation',
    START_OFFBOARDING: 'Start offboarding',
    COMPLETE_OFFBOARDING: 'Complete offboarding',
    REHIRE: 'Rehire',
  } as Record<string, string>,
  stepHelp: {
    START_ONBOARDING: 'Opens the onboarding checklist.',
    ACTIVATE: 'Needs every required onboarding item ticked and the joining date.',
    RESIGN: 'Starts the notice period until the last working day.',
    WITHDRAW_RESIGNATION: 'Returns the employee to active.',
    START_OFFBOARDING: 'Opens the offboarding checklist. Use this for terminations too.',
    COMPLETE_OFFBOARDING: 'Needs every required offboarding item ticked. Removes all roles in this organization.',
    REHIRE: 'Starts onboarding again. The history is kept.',
  } as Record<string, string>,
  stepDate: {
    ACTIVATE: 'Joining date',
    RESIGN: 'Last working day',
    START_OFFBOARDING: 'Exit date',
    REHIRE: 'New joining date',
  } as Record<string, string>,
  reason: 'Reason',
  onboardingChecklist: 'Onboarding checklist',
  offboardingChecklist: 'Offboarding checklist',
  required: 'Required',
  doneBy: (who: string, when: string) => `Done by ${who} · ${when}`,
  noticeUntil: (d: string) => `Notice period until ${d}`,
  exitOn: (d: string) => `Exit date ${d}`,
  checklistClosed: 'No checklist is open. Checklists open when onboarding or offboarding starts.',
  noLifecycleAccess: 'Only HR can change the employment status.',

  // History
  historyEmpty: 'No history yet.',
  historyType: {
    CREATED: 'Record created',
    JOB_CHANGE: 'Job change',
    DETAILS: 'Details updated',
    STATUS: 'Status change',
    ACCOUNT: 'Account linked',
  } as Record<string, string>,
  effective: (d: string) => `Effective ${d}`,
  field: {
    branchId: 'Branch',
    departmentId: 'Department',
    designationId: 'Designation',
    managerId: 'Reports to',
    employmentType: 'Employment type',
    fullName: 'Name',
    phone: 'Phone',
    email: 'Email',
    joiningDate: 'Joining date',
    status: 'Status',
    account: 'Stories account',
  } as Record<string, string>,

  // Access
  accessTitle: 'System access',
  accountLinked: (email: string) => `Signs in to Stories as ${email}.`,
  accountNotLinked: 'Not linked to a Stories account yet, so this person cannot sign in to the staff console.',
  linkAccount: 'Link account',
  linkEmail: 'Their Stories sign-in email',
  linkHint: 'The person must have signed up to Stories with this email.',
  rolesHere: 'Roles here',
  noRoles: 'No roles in this organization.',
  manageRoles: 'Manage roles',
  rolesOffboarded: 'Roles were removed when offboarding completed.',

  // Documents
  navDocuments: 'Documents',
  tabDocuments: 'Documents',
  documentsTitle: 'Documents',
  documentsIntro: 'Documents waiting for verification, and documents that are expiring or have expired.',
  queuePending: 'Awaiting verification',
  queueExpiring: 'Expiring soon',
  queueExpired: 'Expired',
  queueEmpty: { pending: 'Nothing to verify.', expiring: 'Nothing expires soon.', expired: 'No expired documents.' } as Record<string, string>,
  requiredDocs: 'Required documents',
  allDocs: 'On file',
  showHistory: 'Show replaced and removed documents',
  noDocuments: 'No documents on file yet.',
  uploadDocument: 'Upload document',
  documentType: 'Document type',
  documentFile: 'File',
  documentFileHint: 'PDF, JPEG or PNG, up to 5 MB.',
  documentNumber: 'Document number (optional)',
  issuedOn: 'Issued on (optional)',
  issued: (d: string) => `Issued ${d}`,
  expiresOn: 'Expires on',
  fileTooLarge: 'The file is larger than 5 MB.',
  fileWrongType: 'Choose a PDF, JPEG or PNG file.',
  chooseFile: 'Choose a file.',
  open: 'Open',
  verify: 'Verify',
  reject: 'Reject',
  remove: 'Remove',
  rejectTitle: (type: string) => `Reject ${type}?`,
  rejectBody: 'The employee sees the reason and can upload a new copy.',
  removeTitle: (type: string) => `Remove ${type}?`,
  removeBody: 'It stays in the history but no longer counts as on file.',
  uploadedBy: (who: string, when: string) => `Uploaded by ${who} · ${when}`,
  selfUploaded: 'Uploaded by the employee',
  verifiedBy: (who: string) => `Verified by ${who}`,
  rejectedBecause: (why: string) => `Rejected: ${why}`,
  expiresIn: (d: number) => (d < 0 ? `Expired ${-d} day${d === -1 ? '' : 's'} ago` : d === 0 ? 'Expires today' : `Expires in ${d} day${d === 1 ? '' : 's'}`),
  missing: 'Missing',
  docStatus: { PENDING: 'Awaiting verification', VERIFIED: 'Verified', REJECTED: 'Rejected', EXPIRED: 'Expired', SUPERSEDED: 'Replaced', REMOVED: 'Removed', MISSING: 'Missing' } as Record<string, string>,
  employeeCol: 'Employee',
  documentCol: 'Document',
  datesCol: 'Dates',
  verifyUploadedHint: 'Documents you upload for someone else are verified straight away. Documents about yourself need another verifier.',
  todoDocsPending: (n: number) => `${n} document${n === 1 ? '' : 's'} awaiting verification`,
  todoDocsExpiring: (n: number) => `${n} document${n === 1 ? '' : 's'} expiring soon`,
  todoDocsExpired: (n: number) => `${n} document${n === 1 ? ' has' : 's have'} expired`,

  // Document types (HR settings)
  documentTypes: 'Document types',
  documentTypesIntro: 'What HR collects from employees. Required types show as missing on a profile until a verified copy is on file.',
  documentTypeNew: 'New document type',
  documentTypeEdit: 'Edit document type',
  documentTypeName: 'Name',
  documentCategory: 'Category',
  categories: { IDENTITY: 'Identity', ADDRESS: 'Address', STATUTORY: 'Statutory', CONTRACT: 'Contract', EDUCATION: 'Education', EMPLOYMENT: 'Employment', OTHER: 'Other' } as Record<string, string>,
  typeRequired: 'Required for every employee',
  typeHasExpiry: 'Has an expiry date',
  typeReminderDays: 'Remind this many days before expiry',
  typeSelfUpload: 'Employees may upload it themselves',
  typeChecklist: 'Ticks onboarding item',
  typeChecklistNone: 'None',
  typeArchiveTitle: (n: string) => `Archive ${n}?`,
  typeArchiveBody: 'It is no longer offered for new uploads. Documents already on file keep it.',
  typeFlags: { required: 'Required', expiry: 'Expires', self: 'Self-upload' } as Record<string, string>,

  // Settings
  settingsIntro: 'Job titles, the documents HR collects, and the checklists used when people join and leave.',
  designations: 'Designations',
  designationNew: 'New designation',
  designationName: 'Designation name',
  designationsEmpty: 'No designations yet. Add job titles such as Librarian or Branch Manager.',
  designationArchiveTitle: (n: string) => `Archive ${n}?`,
  checklists: 'Checklists',
  checklistsIntro: 'New checklists copy these items; checklists already started keep theirs.',
  itemLabel: 'Item',
  addItem: 'Add item',
  removeItem: 'Remove',
  saveChecklists: 'Save checklists',
  saved: 'Saved.',
};
