/** Staff console strings for People (HRMS). */
export const ht = {
  sectionPeople: 'People',
  navEmployees: 'Employees',
  navHrSettings: 'HR settings',

  employeesTitle: 'Employees',
  employeesIntro: 'Everyone who works here: their job, status and records. Roles and system access are on each profile.',
  addEmployee: 'Add employee',
  searchEmployees: 'Search by name, ID or email',
  allStatuses: 'All statuses',
  allBranchesFilter: 'All branches',
  allDepartments: 'All departments',
  headOffice: 'Head office',
  noEmployees: 'No employees match.',
  noEmployeesYet: 'No employee records yet.',
  backfillTitle: (n: number) => `${n} staff member${n === 1 ? ' has' : 's have'} roles but no employee record`,
  backfillBody: 'They were added before People existed. Create their records now; their employee IDs are kept.',
  backfillAction: 'Create records',
  backfillDone: (created: number, linked: number) => `Created ${created} record${created === 1 ? '' : 's'}${linked ? `, linked ${linked}` : ''}.`,

  colName: 'Name',
  colDesignation: 'Designation',
  colBranch: 'Branch',
  colStatus: 'Status',
  colJoined: 'Joined',

  status: {
    DRAFT: 'Draft',
    ONBOARDING: 'Onboarding',
    ACTIVE: 'Active',
    NOTICE_PERIOD: 'Notice period',
    OFFBOARDING: 'Offboarding',
    OFFBOARDED: 'Offboarded',
  } as Record<string, string>,
  employmentType: { FULL_TIME: 'Full time', PART_TIME: 'Part time', CONTRACT: 'Contract', INTERN: 'Intern' } as Record<string, string>,

  fullName: 'Full name',
  workEmail: 'Email',
  workEmailHint: 'If the person has a Stories account with this email, it is linked now.',
  linkedEmailHint: 'Linked to a Stories account; the email comes from the account.',
  phone: 'Phone',
  branch: 'Branch',
  department: 'Department',
  designation: 'Designation',
  none: 'None',
  manager: 'Reports to',
  employmentTypeLabel: 'Employment type',
  joiningDate: 'Joining date',
  effectiveDate: 'Effective from',
  effectiveHint: 'For job changes. Recorded in the history.',
  changeNote: 'Note (optional)',
  employeeIdHint: 'Leave blank to number automatically with the branch pattern.',

  tabOverview: 'Overview',
  tabPersonal: 'Personal',
  tabBank: 'Bank',
  tabLifecycle: 'Onboarding & exit',
  tabHistory: 'History',
  tabAccess: 'Access',

  job: 'Job',
  contact: 'Contact',
  editDetails: 'Edit details',
  notSet: 'Not set',

  // Personal
  personalTitle: 'Personal and statutory details',
  editPersonal: 'Edit personal details',
  dob: 'Date of birth',
  gender: 'Gender',
  genders: { '': 'Not given', FEMALE: 'Female', MALE: 'Male', OTHER: 'Other' } as Record<string, string>,
  bloodGroup: 'Blood group',
  personalEmail: 'Personal email',
  personalPhone: 'Personal phone',
  currentAddress: 'Current address',
  permanentAddress: 'Permanent address',
  emergency: 'Emergency contact',
  emergencyName: 'Emergency contact name',
  emergencyRelation: 'Relationship',
  emergencyPhone: 'Emergency contact phone',
  pan: 'PAN',
  uan: 'UAN (PF)',
  esiNumber: 'ESI number',
  noPrivateAccess: 'Personal details are visible to HR and finance only.',

  // Bank
  bankTitle: 'Salary account',
  bankNone: 'No bank account recorded yet.',
  bankEdit: 'Change bank account',
  bankAdd: 'Add bank account',
  accountHolder: 'Account holder',
  accountNumber: 'Account number',
  bankName: 'Bank',
  ifsc: 'IFSC',
  reveal: 'Show full number',
  revealNote: 'Showing the full number is recorded in the audit log.',
  hide: 'Hide',
  masked: (last4: string) => `•••• •••• ${last4}`,

  // Lifecycle
  steps: {
    START_ONBOARDING: 'Start onboarding',
    ACTIVATE: 'Mark as joined',
    RESIGN: 'Record resignation',
    WITHDRAW_RESIGNATION: 'Withdraw resignation',
    START_OFFBOARDING: 'Start offboarding',
    COMPLETE_OFFBOARDING: 'Complete offboarding',
    REHIRE: 'Rehire',
  } as Record<string, string>,
  stepHelp: {
    START_ONBOARDING: 'Opens the onboarding checklist.',
    ACTIVATE: 'Needs every required onboarding item ticked and the joining date.',
    RESIGN: 'Starts the notice period until the last working day.',
    WITHDRAW_RESIGNATION: 'Returns the employee to active.',
    START_OFFBOARDING: 'Opens the offboarding checklist. Use this for terminations too.',
    COMPLETE_OFFBOARDING: 'Needs every required offboarding item ticked. Removes all roles in this organization.',
    REHIRE: 'Starts onboarding again. The history is kept.',
  } as Record<string, string>,
  stepDate: {
    ACTIVATE: 'Joining date',
    RESIGN: 'Last working day',
    START_OFFBOARDING: 'Exit date',
    REHIRE: 'New joining date',
  } as Record<string, string>,
  reason: 'Reason',
  onboardingChecklist: 'Onboarding checklist',
  offboardingChecklist: 'Offboarding checklist',
  required: 'Required',
  doneBy: (who: string, when: string) => `Done by ${who} · ${when}`,
  noticeUntil: (d: string) => `Notice period until ${d}`,
  exitOn: (d: string) => `Exit date ${d}`,
  checklistClosed: 'No checklist is open. Checklists open when onboarding or offboarding starts.',
  noLifecycleAccess: 'Only HR can change the employment status.',

  // History
  historyEmpty: 'No history yet.',
  historyType: {
    CREATED: 'Record created',
    JOB_CHANGE: 'Job change',
    DETAILS: 'Details updated',
    STATUS: 'Status change',
    ACCOUNT: 'Account linked',
  } as Record<string, string>,
  effective: (d: string) => `Effective ${d}`,
  field: {
    branchId: 'Branch',
    departmentId: 'Department',
    designationId: 'Designation',
    managerId: 'Reports to',
    employmentType: 'Employment type',
    fullName: 'Name',
    phone: 'Phone',
    email: 'Email',
    joiningDate: 'Joining date',
    status: 'Status',
    account: 'Stories account',
  } as Record<string, string>,

  // Access
  accessTitle: 'System access',
  accountLinked: (email: string) => `Signs in to Stories as ${email}.`,
  accountNotLinked: 'Not linked to a Stories account yet, so this person cannot sign in to the staff console.',
  linkAccount: 'Link account',
  linkEmail: 'Their Stories sign-in email',
  linkHint: 'The person must have signed up to Stories with this email.',
  rolesHere: 'Roles here',
  noRoles: 'No roles in this organization.',
  manageRoles: 'Manage roles',
  rolesOffboarded: 'Roles were removed when offboarding completed.',

  // Documents
  navDocuments: 'Documents',
  tabDocuments: 'Documents',
  documentsTitle: 'Documents',
  documentsIntro: 'Documents waiting for verification, and documents that are expiring or have expired.',
  queuePending: 'Awaiting verification',
  queueExpiring: 'Expiring soon',
  queueExpired: 'Expired',
  queueEmpty: { pending: 'Nothing to verify.', expiring: 'Nothing expires soon.', expired: 'No expired documents.' } as Record<string, string>,
  requiredDocs: 'Required documents',
  allDocs: 'On file',
  showHistory: 'Show replaced and removed documents',
  noDocuments: 'No documents on file yet.',
  uploadDocument: 'Upload document',
  documentType: 'Document type',
  documentFile: 'File',
  documentFileHint: 'PDF, JPEG or PNG, up to 5 MB.',
  documentNumber: 'Document number (optional)',
  issuedOn: 'Issued on (optional)',
  issued: (d: string) => `Issued ${d}`,
  expiresOn: 'Expires on',
  fileTooLarge: 'The file is larger than 5 MB.',
  fileWrongType: 'Choose a PDF, JPEG or PNG file.',
  chooseFile: 'Choose a file.',
  open: 'Open',
  verify: 'Verify',
  reject: 'Reject',
  remove: 'Remove',
  rejectTitle: (type: string) => `Reject ${type}?`,
  rejectBody: 'The employee sees the reason and can upload a new copy.',
  removeTitle: (type: string) => `Remove ${type}?`,
  removeBody: 'It stays in the history but no longer counts as on file.',
  uploadedBy: (who: string, when: string) => `Uploaded by ${who} · ${when}`,
  selfUploaded: 'Uploaded by the employee',
  verifiedBy: (who: string) => `Verified by ${who}`,
  rejectedBecause: (why: string) => `Rejected: ${why}`,
  expiresIn: (d: number) => (d < 0 ? `Expired ${-d} day${d === -1 ? '' : 's'} ago` : d === 0 ? 'Expires today' : `Expires in ${d} day${d === 1 ? '' : 's'}`),
  missing: 'Missing',
  docStatus: { PENDING: 'Awaiting verification', VERIFIED: 'Verified', REJECTED: 'Rejected', EXPIRED: 'Expired', SUPERSEDED: 'Replaced', REMOVED: 'Removed', MISSING: 'Missing' } as Record<string, string>,
  employeeCol: 'Employee',
  documentCol: 'Document',
  datesCol: 'Dates',
  verifyUploadedHint: 'Documents you upload for someone else are verified straight away. Documents about yourself need another verifier.',
  todoDocsPending: (n: number) => `${n} document${n === 1 ? '' : 's'} awaiting verification`,
  todoDocsExpiring: (n: number) => `${n} document${n === 1 ? '' : 's'} expiring soon`,
  todoDocsExpired: (n: number) => `${n} document${n === 1 ? ' has' : 's have'} expired`,

  // Attendance
  navAttendance: 'Attendance',
  navMyAttendance: 'My attendance',
  attendanceIntro: "Who is in today, each person's month, and corrections waiting for a decision.",
  tabToday: 'Day',
  tabMonth: 'Month',
  tabCorrections: 'Corrections',
  tabAttendance: 'Attendance',
  day: 'Day',
  monthLabel: 'Month',
  shiftCol: 'Shift',
  inCol: 'In',
  outCol: 'Out',
  workedCol: 'Worked',
  noShift: 'No fixed hours',
  checkIn: 'Check in',
  checkOut: 'Check out',
  checkInFor: (name: string) => `Check in ${name}`,
  checkOutFor: (name: string) => `Check out ${name}`,
  adjust: 'Adjust',
  adjustTitle: (name: string, date: string) => `Adjust ${name} · ${date}`,
  adjustHint: 'Leave both times empty to clear the day. A check-out earlier than the check-in is the next morning.',
  checkInTime: 'Check-in time',
  checkOutTime: 'Check-out time',
  setShift: 'Shift',
  changeShift: 'Change shift or days off',
  setShiftTitle: (name: string) => `Shift and days off · ${name}`,
  weeklyOffs: 'Weekly days off',
  branchDefault: "Use the branch's days off",
  weekdays: { MON: 'Mon', TUE: 'Tue', WED: 'Wed', THU: 'Thu', FRI: 'Fri', SAT: 'Sat', SUN: 'Sun' } as Record<string, string>,
  dayStatus: { PRESENT: 'Present', HALF_DAY: 'Half day', ABSENT: 'Absent', WEEKLY_OFF: 'Weekly off', HOLIDAY: 'Holiday', ON_LEAVE: 'On leave', IN_PROGRESS: 'Checked in', NOT_IN: 'Not in yet' } as Record<string, string>,
  lateBy: (m: number) => `Late ${m} min`,
  leftEarly: 'Left early',
  missedCheckout: 'No check-out',
  sources: { SELF: 'Self', DESK: 'Desk', ADJUSTED: 'Adjusted', CORRECTION: 'Correction', FINALIZE: 'Month end', LEAVE: 'Leave' } as Record<string, string>,
  noRecords: 'No attendance recorded.',
  noEmployeesHere: 'No employees in your branches.',
  summaryCols: { present: 'Present', halfDays: 'Half days', absent: 'Absent', weeklyOffs: 'Offs', holidays: 'Holidays', leaveDays: 'Leave', lateDays: 'Late', payableDays: 'Payable days' } as Record<string, string>,
  monthOpen: 'This month is open. Summaries appear after it is finalized.',
  monthFinalized: (who: string, when: string) => `Finalized by ${who} · ${when}`,
  monthReopened: 'Reopened. Finalize it again to update the summaries.',
  finalizeFor: 'Finalize for',
  finalize: 'Finalize month',
  finalizeTitle: (month: string, where: string) => `Finalize ${month} for ${where}?`,
  finalizeBody: 'Every day gets its final status (days without a record become absent, weekly off or holiday; a missing check-out counts as half a day) and the month is locked.',
  finalizeDone: (n: number) => `Finalized for ${n} employee${n === 1 ? '' : 's'}.`,
  reopen: 'Reopen month',
  reopenTitle: (month: string) => `Reopen ${month}?`,
  reopenBody: 'Days can be corrected again. Payroll should not use the summaries until the month is finalized again.',
  staleSummary: 'Out of date',
  correctionsEmpty: 'No corrections waiting.',
  requested: (inT: string, outT: string) => `Asked for ${inT || '—'} to ${outT || '—'}`,
  approve: 'Approve',
  rejectCorrectionTitle: (name: string, date: string) => `Reject ${name}'s correction for ${date}?`,
  rejectCorrectionBody: 'The employee sees your reason.',
  todayCard: 'Today',
  checkedInAt: (t: string) => `Checked in at ${t}`,
  checkedOutAt: (t: string) => `Checked out at ${t}`,
  shiftTimes: (name: string, start: string, end: string) => `${name} · ${start}–${end}`,
  notCheckedIn: 'You have not checked in today.',
  dayDone: 'Your day is recorded.',
  requestCorrection: 'Request a correction',
  correctionTitle: 'Request a correction',
  correctionDate: 'Date',
  correctionReason: 'Reason',
  myCorrections: 'My corrections',
  correctionStatus: { PENDING: 'Waiting', APPROVED: 'Approved', REJECTED: 'Rejected' } as Record<string, string>,
  noEmployeeRecord: 'This needs an employee record. Ask HR to add you in People.',
  todoCorrections: (n: number) => `${n} attendance correction${n === 1 ? '' : 's'} to decide`,
  todoFinalize: (m: string) => `Finalize attendance for ${m}`,

  // Leave
  navLeave: 'Leave',
  navMyLeave: 'My leave',
  leaveIntro: "Leave waiting for a decision, who is away, and everyone's balances.",
  myLeaveIntro: 'Your balances for the year and your requests. Days exclude weekly offs and holidays.',
  tabLeave: 'Leave',
  tabRequests: 'Requests',
  tabAway: 'Away',
  tabBalances: 'Balances',
  applyLeave: 'Apply for leave',
  applyLeaveFor: (name: string) => `Leave for ${name}`,
  applyOnBehalf: 'Record leave',
  leaveType: 'Type',
  leaveFrom: 'From',
  leaveTo: 'To',
  leaveHalfDay: 'Half day',
  halfDays: { NONE: 'Full days', FIRST: 'First half', SECOND: 'Second half' } as Record<string, string>,
  halfDayHint: 'A half day is a single date.',
  leaveReason: 'Reason',
  leaveApplied: (days: string) => `Applied for ${days}. It is waiting for approval.`,
  leaveStatus: { PENDING: 'Waiting', APPROVED: 'Approved', REJECTED: 'Rejected', CANCELLED: 'Cancelled' } as Record<string, string>,
  leaveDates: (from: string, to: string) => (from === to ? from : `${from} – ${to}`),
  leaveDatesCol: 'Dates',
  leaveEmpty: 'No leave requests.',
  pendingLeaveEmpty: 'No leave waiting for a decision.',
  awayEmpty: 'Nobody has approved leave this month.',
  balance: 'Balance',
  balanceLeft: (days: string) => `${days} left`,
  balanceDetail: (credited: number, used: number, pending: number) => `Credited ${credited} · used ${used}${pending ? ` · ${pending} waiting` : ''}`,
  unlimited: 'No limit',
  unpaid: 'Unpaid',
  yearLabel: 'Year',
  noBalances: (y: string) => `No balances for ${y} yet. Credit leave to start them.`,
  runAccrual: 'Credit leave',
  accrualTitle: 'Credit leave for a month',
  accrualBody: "Adds each type's monthly or yearly credit to everyone employed that month, and carries unused days into a new year. It runs by itself every day; running it again changes nothing.",
  accrualDone: (n: number, days: number) => (n ? `Credited ${days} days to ${n} ${n === 1 ? 'person' : 'people'}.` : 'Everyone already has this month’s credit.'),
  adjustBalance: 'Adjust balance',
  adjustBalanceTitle: (name: string) => `Adjust leave · ${name}`,
  adjustDays: 'Days (negative to remove)',
  adjustDaysHint: 'For opening balances and corrections. The reason is kept with the entry.',
  approveLeave: (name: string) => `Approve leave for ${name}`,
  rejectLeave: (name: string) => `Reject leave for ${name}`,
  rejectLeaveTitle: (name: string) => `Reject leave · ${name}`,
  rejectLeaveBody: 'The days go back to their balance. Say why, so they know what to do next.',
  cancelLeave: 'Cancel',
  cancelLeaveTitle: 'Cancel this leave?',
  cancelLeaveBody: 'The days go back to the balance and attendance for those days is worked out again.',
  cancelLeaveFor: (from: string) => `Cancel leave from ${from}`,
  cancelNote: 'Note (required when cancelling for someone else)',
  keepLeave: 'Keep it',
  ledger: 'History',
  ledgerKinds: { ACCRUAL: 'Credited', CARRY: 'Carried forward', ADJUST: 'Adjusted', TAKEN: 'Taken', RETURNED: 'Returned' } as Record<string, string>,
  ledgerEmpty: 'Nothing credited or taken yet this year.',
  todoLeave: (n: number) => `${n} leave request${n === 1 ? '' : 's'} to decide`,
  onLeaveToday: 'On leave today',
  leaveTypes: 'Leave types',
  leaveTypesIntro: 'The kinds of leave people can take. Changes apply to future credits and requests; balances already credited stay.',
  leaveTypeNew: 'New leave type',
  leaveTypeEdit: 'Edit leave type',
  leaveTypeName: 'Name',
  leaveTypeCode: 'Short code',
  leaveTypeCodeHint: 'Shown in tables, e.g. CL.',
  leaveQuota: 'Days a year',
  leaveAccrual: 'Credited',
  accruals: { MONTHLY: 'Monthly (a twelfth each month)', YEARLY: 'Yearly (in January; joiners get a share)', MANUAL: 'Only when HR grants it (maternity, bereavement)' } as Record<string, string>,
  leaveCarry: 'Carry into next year (at most, days)',
  leavePaid: 'Paid leave',
  leaveAllowHalf: 'Can be taken for half a day',
  leaveUnlimited: 'No balance (e.g. loss of pay)',
  leaveTypeArchiveTitle: (n: string) => `Archive ${n}?`,
  leaveTypeArchiveBody: 'It is no longer offered or credited. Balances and past leave stay.',
  leaveFlags: (t: { paid: boolean; unlimited: boolean; annualQuota: number; accrual: string; carryForwardMax: number; allowHalfDay: boolean }) =>
    [
      t.unlimited ? 'No balance' : t.accrual === 'MANUAL' ? 'Granted by HR' : `${t.annualQuota} days a year, ${t.accrual === 'MONTHLY' ? 'monthly' : 'yearly'}`,
      t.paid ? 'Paid' : 'Unpaid',
      t.carryForwardMax ? `carries up to ${t.carryForwardMax}` : '',
      t.allowHalfDay ? 'half days' : '',
    ]
      .filter(Boolean)
      .join(' · '),

  // Payroll
  navPayroll: 'Payroll',
  navMyPayslips: 'My payslips',
  payrollIntro: 'Work out a month from finalized attendance, check it, and send it for approval. Approval publishes the payslips.',
  myPayslipsIntro: 'Your payslips appear here once payroll for the month is approved.',
  payrollFor: 'Run for',
  runStatus: { NONE: 'Not prepared', DRAFT: 'Draft', SUBMITTED: 'Waiting for approval', APPROVED: 'Approved' } as Record<string, string>,
  prepareRun: 'Prepare payroll',
  prepareAgain: 'Prepare again',
  prepareDone: (n: number, problems: number) => `Prepared ${n} payslip${n === 1 ? '' : 's'}${problems ? `, ${problems} problem${problems === 1 ? '' : 's'} to fix` : ''}.`,
  submitRun: 'Submit for approval',
  approveRun: 'Approve and publish',
  rejectRun: 'Send back',
  rejectRunTitle: (m: string) => `Send back payroll for ${m}?`,
  rejectRunBody: 'The run goes back to draft. Say what needs to change.',
  approveRunTitle: (m: string) => `Approve payroll for ${m}?`,
  approveRunBody: (n: number, net: string) => `This publishes ${n} payslip${n === 1 ? '' : 's'} (net pay ${net}). Approved payroll can't be changed; corrections go into a later month.`,
  runStale: 'Something changed since this run was prepared (attendance, TDS or other inputs). Prepare it again before submitting.',
  runRejected: (note: string) => `Sent back: ${note}`,
  runPreparedBy: (who: string) => `Prepared by ${who}`,
  runSubmittedBy: (who: string) => `submitted by ${who}`,
  runApprovedBy: (who: string) => `approved by ${who}`,
  ownRunNote: 'Someone other than the person who prepared or submitted this run must approve it.',
  needsFinalizedAttendance: 'Payroll is worked out from finalized attendance. Finalize the month under Attendance first.',
  problemsTitle: 'Problems to fix',
  totalsGross: 'Gross',
  totalsDeductions: 'Deductions',
  totalsNet: 'Net pay',
  totalsEmployerCost: 'Cost to company',
  colPayable: 'Paid days',
  colGross: 'Gross',
  colDeductions: 'Deductions',
  colNet: 'Net pay',
  noSalary: 'No salary',
  inputs: 'TDS and extras',
  inputsTitle: (name: string, m: string) => `TDS and extras · ${name} · ${m}`,
  inputsHint: 'Income tax to deduct this month, and one-off earnings (bonus, arrears) or deductions (advance recovery).',
  tds: 'Income tax (TDS)',
  otherEarnings: 'Other earnings',
  otherDeductions: 'Other deductions',
  addLine: 'Add line',
  lineName: 'Description',
  lineAmount: 'Amount (₹)',
  removeLine: 'Remove',
  downloadPayslip: 'Payslip PDF',
  downloadPayslipFor: (name: string, m: string) => `Payslip PDF for ${name}, ${m}`,
  noPayslips: 'No payslips yet.',
  noRunYet: 'Payroll for this month has not been prepared.',
  salary: 'Salary',
  tabSalary: 'Salary',
  salaryNew: 'New salary',
  salaryTitle: (name: string) => `Salary · ${name}`,
  salaryFrom: 'From month',
  salaryFromHint: 'Applies from this month until a later version.',
  salaryComponents: 'Monthly earnings',
  salaryComponentsHint: 'BASIC (and DA) make up PF wages. Codes are short, like HRA or CONV.',
  componentCode: 'Code',
  componentName: 'Name',
  componentAmount: 'Monthly amount (₹)',
  addComponent: 'Add component',
  salaryPf: 'Provident fund applies',
  salaryEsi: 'ESI applies (when gross is within the limit)',
  salaryPt: 'Professional tax applies',
  salaryEmpty: 'No salary recorded yet.',
  monthlyGross: (n: string) => `${n} a month`,
  salaryVersionFrom: (m: string) => `From ${m}`,
  statutoryOptOut: (pf: boolean, esi: boolean, pt: boolean) => ['PF', 'ESI', 'PT'].filter((_, i) => ![pf, esi, pt][i]).map((x) => `no ${x}`).join(' · '),
  payslips: 'Payslips',
  draftSlip: 'Draft',
  payrollSettings: 'Payroll settings',
  payrollSettingsIntro: 'Provident fund, ESI and professional tax. A new version applies from its month; approved payroll keeps the settings it used.',
  settingsInForce: (m: string) => (m === '2000-01' ? 'Standard rates (never changed)' : `In force from ${m}`),
  settingsNew: 'New version',
  settingsTitle: 'Payroll settings from a month',
  pfSection: 'Provident fund',
  esiSection: 'ESI',
  ptSection: 'Professional tax',
  enabled: 'Deduct it',
  employeeRate: 'Employee rate (%)',
  employerRate: 'Employer rate (%)',
  epsRate: 'Pension (EPS) share of employer rate (%)',
  wageCeiling: 'Wage ceiling (₹)',
  capAtCeiling: 'Only on wages up to the ceiling',
  grossLimit: 'Covers monthly gross up to (₹)',
  ptSlabs: 'Monthly slabs',
  ptSlabFrom: 'Gross from (₹)',
  ptSlabAmount: 'Tax (₹)',
  addSlab: 'Add slab',
  februaryAmount: 'February amount (₹, empty = same)',
  settingsSummary: (st: { pf: { enabled: boolean; employeeRate: number; wageCeiling: number }; esi: { enabled: boolean; employeeRate: number; grossLimit: number }; pt: { enabled: boolean; slabs: { from: number; amount: number }[] } }) =>
    [
      st.pf.enabled ? `PF ${st.pf.employeeRate}% (ceiling ₹${st.pf.wageCeiling.toLocaleString('en-IN')})` : 'No PF',
      st.esi.enabled ? `ESI ${st.esi.employeeRate}% up to ₹${st.esi.grossLimit.toLocaleString('en-IN')}` : 'No ESI',
      st.pt.enabled ? `PT ${st.pt.slabs.filter((x) => x.amount).map((x) => `₹${x.amount} from ₹${x.from.toLocaleString('en-IN')}`).join(', ') || 'none'}` : 'No PT',
    ].join(' · '),
  todoPayroll: (n: number) => `${n} payroll run${n === 1 ? '' : 's'} to approve`,

  // Notifications
  notifications: 'Notifications',
  notificationsLabel: (n: number) => (n ? `Notifications, ${n} unread` : 'Notifications'),
  markAllRead: 'Mark all read',
  noNotifications: 'Nothing new. Decisions on your leave, attendance, documents and payslips appear here.',
  unread: 'Unread',

  // My profile (self-service)
  navMyProfile: 'My profile',
  myProfileIntro: 'Your job details, today, and everything HR keeps for you.',
  myAttendanceCard: 'Attendance this month',
  myAttendanceSummary: (present: number, half: number, leave: number, absent: number) =>
    [`${present} present`, half && `${half} half day${half === 1 ? '' : 's'}`, leave && `${leave} on leave`, absent && `${absent} absent`].filter(Boolean).join(' · '),
  noDaysYet: 'No days recorded yet.',
  myLeaveCard: 'Leave left this year',
  myLeaveWaiting: (n: number) => `${n} request${n === 1 ? '' : 's'} waiting`,
  myPayslipCard: 'Latest payslip',
  noPayslipYet: 'None yet.',
  openPage: (name: string) => `Open ${name}`,
  myDetails: 'Job details',
  myDocuments: 'My documents',
  myTasks: 'My tasks',
  myTasksPlaceholder: 'Tasks and checklists assigned to you will appear here when the Tasks module arrives.',

  // People overview (dashboard)
  navOverview: 'Overview',
  overviewIntro: 'Headcount, who is in today, what is waiting, and this month at a glance.',
  headcount: 'Headcount',
  statActive: 'Active',
  statOnboarding: 'Joining',
  statLeaving: 'Leaving',
  statJoined: 'Joined this month',
  statLeft: 'Left this month',
  today: 'Today',
  todayIn: 'Checked in',
  todayOnLeave: 'On leave',
  todayNotIn: 'Not in yet',
  waitingOnYou: 'Waiting on you',
  nothingWaiting: 'Nothing is waiting on you.',
  byBranch: 'By branch',
  byDepartment: 'By department',
  noDepartment: 'No department',
  leaveThisMonth: (m: string) => `Leave in ${m}`,
  noLeaveThisMonth: 'No approved leave this month.',
  daysOf: (days: string, type: string) => `${days} of ${type}`,
  lastPayroll: 'Last approved payroll',
  noApprovedPayroll: 'No approved payroll yet.',
  payrollSummary: (month: string, where: string) => `${month} · ${where}`,

  // Shifts and holidays (HR settings)
  shifts: 'Shifts',
  shiftsIntro: 'Working hours used to work out lateness, half days and full days.',
  shiftNew: 'New shift',
  shiftEdit: 'Edit shift',
  shiftName: 'Shift name',
  shiftStart: 'Starts',
  shiftEnd: 'Ends',
  shiftBreak: 'Break (minutes)',
  shiftGrace: 'Late after (minutes past start)',
  shiftHalf: 'Half day from (minutes worked)',
  shiftFull: 'Full day from (minutes worked)',
  shiftArchiveTitle: (n: string) => `Archive ${n}?`,
  shiftArchiveBody: 'It can no longer be assigned. People on it keep it until they are moved.',
  shiftsEmpty: 'No shifts yet. Without a shift, a day counts from hours worked and nobody is late.',
  holidays: 'Holidays',
  holidaysIntro: 'Holidays count as paid days off. Leave the branches empty for the whole organization.',
  holidayNew: 'Add holiday',
  holidayName: 'Holiday',
  holidayDate: 'Date',
  holidayBranches: 'Branches',
  holidayAllBranches: 'All branches',
  holidayBranchesHint: 'Leave all unticked for a holiday at every branch.',
  holidaysEmpty: (y: string) => `No holidays for ${y} yet.`,
  holidayRemove: 'Remove',

  // Document types (HR settings)
  documentTypes: 'Document types',
  documentTypesIntro: 'What HR collects from employees. Required types show as missing on a profile until a verified copy is on file.',
  documentTypeNew: 'New document type',
  documentTypeEdit: 'Edit document type',
  documentTypeName: 'Name',
  documentCategory: 'Category',
  categories: { IDENTITY: 'Identity', ADDRESS: 'Address', STATUTORY: 'Statutory', CONTRACT: 'Contract', EDUCATION: 'Education', EMPLOYMENT: 'Employment', OTHER: 'Other' } as Record<string, string>,
  typeRequired: 'Required for every employee',
  typeHasExpiry: 'Has an expiry date',
  typeReminderDays: 'Remind this many days before expiry',
  typeSelfUpload: 'Employees may upload it themselves',
  typeChecklist: 'Ticks onboarding item',
  typeChecklistNone: 'None',
  typeArchiveTitle: (n: string) => `Archive ${n}?`,
  typeArchiveBody: 'It is no longer offered for new uploads. Documents already on file keep it.',
  typeFlags: { required: 'Required', expiry: 'Expires', self: 'Self-upload' } as Record<string, string>,

  // Settings
  settingsIntro: 'Job titles, shifts and holidays, leave types, payroll settings, the documents HR collects, and the checklists used when people join and leave.',
  designations: 'Designations',
  designationNew: 'New designation',
  designationName: 'Designation name',
  designationsEmpty: 'No designations yet. Add job titles such as Librarian or Branch Manager.',
  designationArchiveTitle: (n: string) => `Archive ${n}?`,
  checklists: 'Checklists',
  checklistsIntro: 'New checklists copy these items; checklists already started keep theirs.',
  itemLabel: 'Item',
  addItem: 'Add item',
  removeItem: 'Remove',
  saveChecklists: 'Save checklists',
  saved: 'Saved.',
};
