import type { AuthFailureCode } from '../auth/models';

// All user-facing copy lives here so it can move to an i18n library unchanged.
export const t = {
  appTitle: 'Stories',
  tagline: 'Every book begins a new story.',
  signInTitle: 'Welcome back',
  signInSubtitle: 'Sign in to borrow, exchange and discover your next book.',
  emailLabel: 'Email',
  passwordLabel: 'Password',
  signInButton: 'Sign in',
  createAccountButton: 'Create an account',
  haveAccountButton: 'I already have an account',
  createAccountTitle: 'Join Stories',
  createAccountSubtitle: "Create your account. You'll choose a subscription next.",
  fullNameLabel: 'Full name',
  continueWithGoogle: 'Continue with Google',
  forgotPassword: 'Forgot password?',
  resetEmailSent: (email: string) => `If an account exists for ${email}, a reset link is on its way.`,
  orDivider: 'or',
  validationEmail: 'Enter a valid email address.',
  validationPassword: 'Use at least 8 characters.',
  validationName: 'Enter your name.',
  navHome: 'Home',
  navExplore: 'Explore',
  navMyBooks: 'My Books',
  navMembership: 'Membership',
  navProfile: 'Profile',
  greeting: (name: string) => `Hello, ${name}`,
  greetingFallback: 'Hello, reader',
  noMembershipTitle: 'No membership linked yet',
  noMembershipMessage:
    'Subscriptions open soon. Once you subscribe you can borrow within your plan and exchange books as often as you like.',
  meNotLinked: (email: string) =>
    `We couldn't find a library membership for ${email}. Ask your branch to add this email to your membership, then open this page again. New to Stories? Visit a branch to join.`,
  meVerifyEmail: (email: string) => `Verify ${email} first (check your inbox for the link), then open this page again to see your membership.`,
  meViewing: 'Showing membership of',
  meChild: 'child',
  meFamily: 'family',
  meNoPlan: 'No active plan',
  meActive: 'Active',
  meRenewSoon: (when: string) => `Renew ${when}`,
  mePlan: 'Plan',
  meRenewsOn: 'Renews on',
  meEndedOn: 'Ended on',
  meBooksOut: 'Books with you',
  meBooksOfMax: (n: number, max: number) => `${n} of ${max}`,
  meDeposit: 'Security deposit',
  mePaymentDue: (plan: string, amount: string) => `Complete your payment: ${plan}, ${amount}`,
  meReadyToCollect: (title: string, until: string) => `“${title}” is ready to collect${until ? ` until ${until}` : ''}`,
  meRenewPrompt: 'Your plan ends soon: renew it',
  meSubscribePrompt: 'Choose a plan to start borrowing',
  meBorrowedNow: 'Borrowed now',
  meNothingBorrowed: 'No books with you right now.',
  meFindBooks: 'Find books to read',
  meSince: (date: string) => `since ${date}`,
  meReturned: (from: string, to: string) => `${from} – ${to}`,
  meSearchBooks: 'Search by title, author or ISBN',
  meShowingFor: (age: string) => `Showing books for ${age.toLowerCase()}.`,
  meNoBooksFound: 'No books match your search',
  meOnShelf: (a: number, total: number) => `${a} of ${total} on the shelf`,
  meNotStocked: 'not stocked here: join the queue',
  meAlreadyReserved: 'Reserved',
  meReserveHere: 'Reserve',
  meJoinQueue: 'Join the queue',
  meReservedHeld: 'Reserved: a copy is set aside for you. See My Books for how long it is held.',
  meReservedWaiting: 'You are in the queue. We will set a copy aside as soon as one is free.',
  meReservations: 'Reservations',
  meNoReservations: 'No reservations.',
  meHeldUntil: (until: string) => `Ready to collect${until ? ` until ${until}` : ''}`,
  meWaitingSince: (date: string) => `In the queue since ${date}`,
  meHistory: 'History',
  meNoHistory: 'Books you return and past reservations appear here.',
  meReservationClosed: (status: string, date: string) => `Reservation ${status.toLowerCase()} · ${date}`,
  meTerm: (from: string, to: string) => `${from} – ${to}`,
  meTermDetail: (n: number) => `Borrow up to ${n} books at a time and exchange as often as you like.`,
  meNeverSubscribed: 'No subscriptions yet.',
  meCompletePayment: 'Complete your payment',
  mePendingFor: (plan: string) => `${plan} starts as soon as it is paid.`,
  meFee: 'Plan fee',
  meDepositTopUp: 'Refundable deposit',
  meTotal: 'Total',
  mePayOnline: 'Pay online (UPI, card, net banking)',
  meIHavePaid: 'I have paid: check now',
  mePayOpened: 'The payment page opened in a new tab. Come back here after paying.',
  mePaid: 'Payment received. Your plan is active.',
  meNotPaidYet: "We haven't received the payment yet. If you just paid, wait a minute and check again.",
  mePayAtCounter: (branch: string) => `Pay at ${branch} (cash, UPI or card). Online payment isn't available at this branch yet.`,
  meChooseAnother: 'Cancel and choose another plan',
  meRenewOrChange: 'Renew or change your plan',
  meChoosePlan: 'Choose a plan',
  meNoPlans: 'No plans are available for this membership right now. Please ask your branch.',
  meRenewWindow: 'Renewals open shortly before your current plan ends; the new term starts when the current one ends.',
  meWasPrice: (p: string) => `usually ${p}`,
  meBooksAtATime: (n: number) => `${n} books at a time`,
  meRefundableDeposit: (p: string) => `+ ${p} refundable deposit (once)`,
  meChoose: 'Choose',
  mePayments: 'Payments',
  meNoPayments: 'No payments yet.',
  meDate: 'Date',
  meFor: 'For',
  meMethod: 'Method',
  meAmount: 'Amount',
  meSubscriptionHistory: 'Subscription history',
  meDepositHeld: (amount: string) => `The library holds ${amount} for you. It is refunded when you close your membership.`,
  meNoDeposit: 'No deposit held.',
  meMembershipDetails: 'Membership details',
  meName: 'Name',
  meMemberCode: 'Member code',
  meDob: 'Date of birth',
  meMobile: 'Mobile',
  meEmail: 'Email',
  meGuardian: 'Guardian',
  meLibrary: 'Library',
  meBorrowedSoFar: 'Borrowed so far',
  meLifetime: (loans: number, exchanges: number) => `${loans} books · ${exchanges} exchanges`,
  meChangeDetails: 'To change these details, please ask your branch.',
  idCardAlt: (name: string, code: string) => `Library ID card of ${name}, member code ${code}`,
  idCardMember: 'Library member',
  idCardGuardian: (name: string) => `Guardian: ${name}`,
  idCardValid: (date: string) => `Plan valid until ${date}`,
  idCardFoot: 'Show this card at the desk to borrow and return books.',
  idCardFootPhone: (phone: string) => `Show this card at the desk · ${phone}`,
  idCardTitle: 'Library ID card',
  idCardIntro: 'Show the QR code at the desk to borrow and return books. Download it to your phone or print it.',
  idCardDownload: 'Download',
  idCardPrint: 'Print',
  idCardShow: 'Show my ID card',
  profileSignedInAs: (email: string) => `Signed in as ${email}`,
  signOut: 'Sign out',
  loading: 'Loading…',

  // Shared
  errorGeneric: 'Something went wrong on our side. Please try again.',
  errorNetwork: 'You appear to be offline. Check your connection and try again.',
  errorLoad: "We couldn't load this. Check your connection and try again.",
  errorServerOutdated:
    "This feature needs the latest server update, which hasn't been deployed yet. Ask the administrator to run `npm run deploy:backend`, then try again.",
  errorIndex: 'This list is still being set up on the server (a database index is building). Try again in a few minutes; if it persists, run the backend deploy again.',
  errorForbidden: "You don't have permission to see this.",
  retry: 'Try again',
  cancel: 'Cancel',
  save: 'Save',
  saving: 'Saving…',
  create: 'Create',
  edit: 'Edit',
  archive: 'Archive',
  close: 'Close',
  required: 'Required',
  reasonLabel: 'Reason',
  reasonHint: 'Recorded in the audit log.',
  allBranches: 'All branches',
  active: 'Active',
  archived: 'Archived',
  revoked: 'Revoked',
  suspended: 'Suspended',
  notFoundTitle: 'Page not found',
  noAccessTitle: "You don't have access to this page",
  noAccessMessage: 'Ask an administrator if you think you should.',

  // Staff console
  consoleTitle: 'Stories Console',
  memberView: 'Member view',
  staffConsole: 'Staff console',
  organization: 'Organization',
  branch: 'Branch',
  navDashboard: 'Dashboard',
  navOrganizations: 'Organizations',
  navBranches: 'Branches',
  navDepartments: 'Departments',
  navStaff: 'Staff & roles',
  navAudit: 'Audit log',
  sectionLibrary: 'Library',
  sectionMembers: 'Members',
  sectionOrganization: 'Organization',
  sectionPersonal: 'Personal',
  navAppearance: 'Appearance',
  apIntro: 'Choose how Stories looks for you. Changes apply straight away and are remembered on this device.',
  apTheme: 'Theme',
  apSystem: 'Match device',
  apSystemHint: 'Follows light or dark mode',
  apLight: 'Light',
  apDark: 'Dark',
  apAccent: 'Accent colour',
  apTextSize: 'Text size',
  apDefault: 'Default',
  apLarge: 'Large',
  apLarger: 'Larger',
  apDensity: 'Density',
  apComfortable: 'Comfortable',
  apComfortableHint: 'Roomy, easy to tap',
  apCompact: 'Compact',
  apCompactHint: 'More rows on screen',
  apCorners: 'Corners',
  apRounded: 'Rounded',
  apSquare: 'Square',
  apContrast: 'Contrast',
  apMoreContrast: 'More contrast',
  apMoreContrastHint: 'Darker secondary text and borders',
  apMotion: 'Motion',
  apReduceMotion: 'Reduce motion',
  apReset: 'Reset to default',
  apSaved: 'Saved automatically.',
  apPreview: 'Preview',
  apPreviewText: 'This is how pages, buttons and tables will look.',
  apPrimaryButton: 'Save changes',
  apSampleField: 'Book title',
  apSampleMember: 'Member',
  apSampleStatus: 'Status',
  apSampleActive: 'Active',
  apSampleDue: 'Renewal due',
  navDesk: 'Circulation desk',
  navCatalogue: 'Catalogue',
  navInventory: 'Inventory',
  navReservations: 'Reservations',
  navTransfers: 'Transfers',
  navMembers: 'Members',
  navPlans: 'Subscription plans',
  navDepositApprovals: 'Deposit approvals',
  filterPlaceholder: 'Filter…',
  scanPlaceholder: 'Scan the QR code or type the code',
  scanAdd: 'Add',
  noBranchTitle: 'No branch to work at',
  noBranchMessage: 'You need a role at an active branch to use this page.',
  noOrgTitle: 'No organization yet',
  noOrgMessage: 'Create the first organization to start setting up Stories.',

  dashboardTitle: 'What needs doing',
  dashboardAllClear: 'Nothing needs your attention right now.',
  todoCreateOrg: 'Create your first organization',
  todoCreateBranch: 'Add a branch to this organization',
  todoAddStaff: 'Give your team their roles',
  todoVerifyEmail: 'Verify your email address',

  orgsTitle: 'Organizations',
  orgNew: 'New organization',
  orgName: 'Organization name',
  orgType: 'Type',
  orgCorporate: 'Corporate (company owned)',
  orgFranchise: 'Franchise',
  orgsEmpty: 'No organizations yet.',

  branchesTitle: 'Branches',
  branchNew: 'New branch',
  branchEdit: 'Edit branch',
  branchCode: 'Branch code',
  branchCodeHint: '2–8 letters or digits, e.g. CEN. Cannot be changed later.',
  branchName: 'Branch name',
  addressLine1: 'Address line 1',
  addressLine2: 'Address line 2 (optional)',
  city: 'City',
  state: 'State',
  postalCode: 'PIN code',
  phone: 'Phone',
  contactEmail: 'Email (optional)',
  hoursTitle: 'Opening hours',
  closedDay: 'Closed',
  branchesEmpty: 'No branches yet.',
  branchesMine: 'The branches you work at.',
  branchArchiveTitle: (name: string) => `Archive ${name}?`,
  branchArchiveBody: 'The branch stays in history and reports but can no longer be edited or used.',
  companyOwned: 'Company owned',
  franchise: 'Franchise',

  departmentsTitle: 'Departments',
  departmentNew: 'New department',
  departmentName: 'Department name',
  departmentScope: 'Applies to',
  departmentsEmpty: 'No departments yet.',
  departmentArchiveTitle: (name: string) => `Archive ${name}?`,
  rename: 'Rename',

  staffTitle: 'Staff & roles',
  staffAdd: 'Add staff member',
  staffEditRoles: 'Edit roles',
  staffEmail: 'Email address',
  staffEmailHint: 'The person must have signed up to Stories with this email.',
  staffRoles: 'Roles',
  staffBranches: 'Branches',
  staffRevoke: 'Remove roles',
  staffRevokeTitle: (name: string) => `Remove all roles for ${name}?`,
  staffRevokeBody: 'They keep their Stories account but lose staff access in this organization.',
  staffEmpty: 'No staff yet. Add the first team member.',
  staffYou: 'You',

  auditTitle: 'Audit log',
  auditEmpty: 'No activity recorded yet.',
  auditWhen: 'When',
  auditAction: 'Action',
  auditEntity: 'Record',
  auditActor: 'By',
  auditDetails: 'Details',
  auditSystem: 'System (automatic)',
  loadMore: 'Load more',

  setupTitle: 'Set up administration',
  setupBody: 'The owner account can claim the first Super Admin role once. Other people get their roles from an administrator.',
  setupClaim: 'Become Super Admin',
  setupDone: "You're now the Super Admin.",
  setupOpenConsole: 'Open the staff console',
  verifyTitle: 'Verify your email first',
  verifyBody: (email: string) => `We sent a verification link to ${email}. Open it, then come back here.`,
  verifyResend: 'Send the link again',
  verifySent: 'Verification email sent.',
  verifyDone: "I've verified it",
} as const;

export const authErrorMessage: Record<AuthFailureCode, string> = {
  invalidCredentials: "That email and password don't match. Check them and try again, or reset your password.",
  emailInUse: 'An account already exists for this email. Sign in instead.',
  weakPassword: 'Choose a stronger password with at least 8 characters.',
  tooManyRequests: 'Too many attempts. Wait a few minutes, then try again.',
  network: 'You appear to be offline. Check your connection and try again.',
  popupClosed: 'Google sign-in was cancelled.',
  userDisabled: 'This account has been disabled. Please contact Stories support.',
  providerDisabled: "This sign-in method isn't switched on yet. Please contact Stories support.",
  popupBlocked: 'Your browser blocked the Google sign-in window. Allow pop-ups for this site and try again.',
  unauthorizedDomain: "Sign-in isn't allowed from this web address yet. Please contact Stories support.",
  unknown: 'Please try again. If it keeps happening, contact your branch.',
};
