// Settings → WhatsApp (docs/WHATSAPP.md).
export const wt = {
  nav: 'WhatsApp',
  title: (branch: string) => `WhatsApp · ${branch}`,
  intro: 'Send members and staff WhatsApp messages from this branch’s WhatsApp Business number: welcomes, payments, renewals, issued and returned books, reservations and staff notifications.',
  guide: 'Step-by-step setup guide',
  connection: 'Connection',
  connectedAs: (name: string, phone: string) => `Connected: ${name} · ${phone}`,
  notConnected: 'Not set up yet. Enter the three values from Meta below.',
  off: 'Sending is switched off for this branch.',
  enabled: 'Send WhatsApp messages from this branch',
  phoneNumberId: 'Phone number ID',
  phoneNumberIdHint: 'Meta → WhatsApp → API Setup → “Phone number ID” (digits only).',
  wabaId: 'WhatsApp Business Account ID',
  wabaIdHint: 'Shown just below the Phone number ID on the same page.',
  token: 'Permanent access token',
  tokenHint: 'Business Settings → System users → Generate token (whatsapp_business_messaging, whatsapp_business_management).',
  tokenSaved: 'Saved. Leave empty to keep it.',
  appSecret: 'App secret (recommended)',
  appSecretHint: 'App settings → Basic → App secret. Lets Stories check that delivery updates really come from Meta.',
  language: 'Language of the messages',
  saveConnection: 'Save and check with Meta',
  saved: 'Saved. Meta confirmed the number.',
  webhook: 'Delivery updates (webhook)',
  webhookIntro: 'Paste these in Meta, not here: developers.facebook.com → your app → WhatsApp → Configuration → Webhook → Edit → Verify and save. Then under Webhook fields, subscribe to “messages” and “message_template_status_update”.',
  callbackUrl: 'Callback URL',
  verifyToken: 'Verify token',
  copy: 'Copy',
  copied: 'Copied',
  testTitle: 'Send a test message',
  testTo: 'Mobile number',
  testHello: 'Send “hello_world”',
  testSent: 'Sent. Check the phone in a few seconds.',
  messages: 'Messages',
  messagesIntro: 'Each message is a WhatsApp “template”: write the wording here, submit it to Meta for approval (usually minutes), then switch it on.',
  checkApprovals: 'Check approvals',
  checked: (n: number) => `Checked ${n} templates with Meta.`,
  audience: { MEMBER: 'To members', STAFF: 'To staff' } as Record<string, string>,
  status: {
    NOT_SUBMITTED: 'Not submitted',
    PENDING: 'Waiting for Meta',
    APPROVED: 'Approved',
    REJECTED: 'Rejected',
    PAUSED: 'Paused by Meta',
    DISABLED: 'Disabled by Meta',
  } as Record<string, string>,
  on: 'On',
  off_: 'Off',
  edit: 'Edit wording',
  submit: 'Submit to Meta',
  submitted: (s: string) => `Sent to Meta for review (${s.toLowerCase()}).`,
  sendTest: 'Send test',
  editTitle: (label: string) => `Message: ${label}`,
  when: 'Sent when',
  body: 'Wording',
  bodyHint: 'Click a value to insert it. A message can’t start or end with a value. Up to 1,024 characters.',
  insert: 'Insert',
  templateName: 'Template name in Meta',
  templateNameHint: 'Lower-case letters, digits and underscores. Change it if Meta rejected a wording (a name can be reused only after 30 days).',
  sendThis: 'Send this message',
  preview: 'Preview (with sample values)',
  changedNote: 'Changing the wording or name means submitting it to Meta again.',
  reasons: {
    INCORRECT_CATEGORY: 'Meta thinks this reads like marketing, not a transactional update. Reword it as a plain account update (e.g. “Your membership at … is registered. Member ID: …”), then submit again.',
    INVALID_FORMAT: 'Meta could not accept the format: check that no value is at the very start or end and there are no line breaks or emojis around values.',
    TAG_CONTENT_MISMATCH: 'The wording does not match the category: make it a plain update about the member’s account or books.',
    PROMOTIONAL: 'Meta treats this as promotional. Remove offers or invitations and keep it a plain update.',
    ABUSIVE_CONTENT: 'Meta flagged the wording. Rephrase it.',
    SCAM: 'Meta flagged the wording as suspicious. Rephrase it and avoid links that look shortened.',
  } as Record<string, string>,
  needsApproval: 'Switch on after Meta approves it; until then nothing is sent.',
  log: 'Message log',
  logWhen: 'When',
  logMessage: 'Message',
  logTo: 'To',
  logState: 'Status',
  logEmpty: 'No messages yet.',
  logStatus: {
    QUEUED: 'Queued',
    SENDING: 'Sending',
    SENT: 'Sent',
    DELIVERED: 'Delivered',
    READ: 'Read',
    FAILED: 'Failed',
    SKIPPED: 'Not sent',
  } as Record<string, string>,
  refresh: 'Refresh',
  setUpFirst: 'Save the connection first.',
};
